 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

#include "RooFit.h"
#include "Riostream.h" 
#include "RooDalitzBS.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "RooRandom.h"
#include <math.h> 
#include "TMath.h" 
//#include "Jpsihh_dlz.h"
//ClassImp(RooDalitzTimeCP) 

int isPhspRes = 0; // 0/1, for Resonance / PHSP
int nacc = 0;

RooDalitzBS::RooDalitzBS(const char *name, const char *title,
                         RooAbsReal& mhh, //m(hh)
                         RooAbsReal& coshh, //cos(hh)
                         RooAbsReal& cosH, //cos(jpsi)
                         RooAbsReal& chi, //chi angle
                         RooAbsReal& dgover2g,
                         RooRealVar& phis,
                         TList *cpList, 
				 TList *resList,
                         TList *effList,
                         double FFR,
                         double FFB
				 ):
  RooAbsPdf(name,title),
  RooDalitzAmplitude(resList, cpList, effList,0,3,FFR,FFB),
  _mhh("mhh","invariant mass pipi",this,mhh),
  _coshh("coshh","cos(theta_hh)",this,coshh),
  _cosH("cosH","cos(Helicity of J/psi", this, cosH),
  _chi("chi","angle of two decay planes", this, chi),
  _dgover2g("dgover2g","Delta Gamma/2Gamma", this, dgover2g),
  _phis("phis","phis",this,phis),
  _resParams("resParams", "Parameters for resonaces", this),
  _cpParams("cpParams", "Parameters for CP violation", this),  
  _Rsum(0),  _RsumInt(0), _RInterf(0), _RInterfInt(0),
  _redoInt(1)
{ 
  //Constructor
  int ir(0);  
  TIterator* coefIter=_resList->MakeIterator();
  while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
    RooArgList ires = (*Ires);
    RooArgList icp = *(RooArgList*)(_cpList->At(ir));    
    int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();
    //     std::cout << "type " << type << std::endl;
    //     std::cout  << type << std::endl;
    ir++;
//    if (type!=1&&type!=2&&type!=3&&type!=4) continue;
    // double m0 = ((RooAbsReal&)ires[2]).getVal();
    _cpParams.add(icp[0]);
    _cpParams.add(icp[1]);
    
    if(type==1) { //breit wigner
      _resParams.add(ires[0]);
      _resParams.add(ires[1]);
      _resParams.add(ires[2]);
      _resParams.add(ires[3]);
      int Spin = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
      if(Spin>0) {
        _resParams.add(ires[4]);
        _resParams.add(ires[5]);
        _resParams.add(ires[6]);
        _resParams.add(ires[7]);
        _cpParams.add(icp[2]);
        _cpParams.add(icp[3]);
        _cpParams.add(icp[4]);
        _cpParams.add(icp[5]);
        
      }
    } else if(type==2) { //f0 flatte
      _resParams.add(ires[0]);
      _resParams.add(ires[1]);
      _resParams.add(ires[2]);
      _resParams.add(ires[3]);      
      _resParams.add(ires[4]);        
    } else if(type==3||type==4) { //noresonace
      _resParams.add(ires[0]);
      _resParams.add(ires[1]);
    } else if(type==10) {//Spline
      std::cout << " Spline" << std::endl;
      for(int i=0; i<ires.getSize()-1; ++i) _resParams.add(ires[i]);
      MakeSpline(ires);
    }
  }
  delete coefIter;
  _pdfmax = new Double_t; *_pdfmax = -1;
//  _NormEFF = NormalEff();
  std::cout << " TO calculate DPTermsIntegral " << std::endl;
  CalCoupling();
  DPTermsIntegralMethod1();
  
  //eff
/*  for(int i=0;i<20; ++i) 
    cout << "eff " << i << " " <<  efficiency(1.0,-1.+0.1*i+0.05) << " " 
       << efficiency(1.5,-1.+0.1*i+0.05) << std::endl;
       */
}


RooDalitzBS::RooDalitzBS(const RooDalitzBS& other, const char* name) :  
  RooAbsPdf(other,name), 
  RooDalitzAmplitude(other),
  _mhh("mhh",this,other._mhh),
  _coshh("coshh",this,other._coshh),
  _cosH("cosH",this,other._cosH),
  _chi("chi",this, other._chi),
  _dgover2g("dgover2g",this, other._dgover2g),
  _phis("phis",this,other._phis),
  _resParams("resParams", this, other._resParams),
  _cpParams("cpParams", this, other._cpParams),
  _Rsum(other._Rsum),
  _RsumInt(other._RsumInt),
  _RInterf(other._RInterf),
  _RInterfInt(other._RInterfInt),
  HH(other.HH),
  _redoInt(other._redoInt)
{ 
  //Copy constructor
  _pdfmax = other._pdfmax;
} 

void RooDalitzBS::setPhspRes( int isPhsp ){
   isPhspRes = isPhsp;
}

//_____________________________________________________________________________
Int_t RooDalitzBS::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const
{
  // Advertize existance of own integration over the Dalitz plot.

   std::cout<<"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"<<std::endl;
   std::cout<<"Requested integration over these variables: "<<std::endl;
   allVars.Print("V");
   std::cout<<"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"<<std::endl<<std::endl;

  RooArgSet List;
  List.add(*(_chi.absArg()));
  List.add(*(_cosH.absArg()));
  List.add(*(_coshh.absArg()));
  List.add(*(_mhh.absArg()));
  if( matchArgs(allVars, analVars, List) )  return 4;
  return 0 ;
}
/////////////////
//Integration //
///////////////
Double_t RooDalitzBS::analyticalIntegral(Int_t code, const char* rangeName) const
{
  switch(code) {
  case 4:
    break;
  default: assert(0);
  }

//  std::cout << "Integral code " << code << std::endl;
  
//  return 1.0;
  DPTermsIntegral(); 
//  std::cout << "INt " <<  _RsumInt - _dgover2g*_RInterfInt.Re() << std::endl;
  
  return _RsumInt - _dgover2g*_RInterfInt.Re();
}


///////////////////////////////////////////////////////////////////////
//
//                  Total PDF
//
//////////////////////////////////////////////////////////////////////
void RooDalitzBS::DPTerms() const//Double_t &Rsum, Double_t &Rdif, TComplex &RInterf) {
{
  // Evaluate |A|^2 +/- |Abar|^2 term in the B0-B0bar time-evolution equation. 
  _Rsum = 0;
  _RInterf = 0;
  //double Rsum(0), Rdif(0);
  //TComplex RInterf(0);
  if(!kine_limits(_mhh))   return;
  if(fabs(_cosH)>1||fabs(_coshh)>1) return;  
  double m2pp = _mhh*_mhh;
  double xeff;
  xeff = efficiency(_mhh,_coshh,_cosH,_chi);//efficiency(_mhh,_coshh)*effcosH(m2p

  if( nacc<2 ){ cout<<" angular efficiency "<<xeff<<" "<<endl; nacc++; }
//  if(_mhh<1.2) xeff = 0.0;
//  double xeff = efficiency(_mhh,_coshh)*effcosH(m2pp, _cosH)*effchi(m2pp,_chi);
  double pB = getpB(_mhh);
  double pR = getpR(_mhh);
  double effphsp = pR*pB*xeff;

  if( isPhspRes ){
     _Rsum = effphsp;
     return;
  }

  Jpsihh_dlz *xdlz = new Jpsihh_dlz();
  //std::cout << "_Rsum _Rdif _RInterf " << _Rsum << " " << _Rdif << " " << _RInterf << std::endl;
  filldlz(*xdlz, _mhh, _coshh);
  TComplex H0(0), Hp(0), Hm(0);
  TComplex H0bar(0), Hpbar(0), Hmbar(0);
  amplitude(0,*xdlz, H0, H0bar);
  amplitude(1,*xdlz, Hp, Hpbar);
  amplitude(-1,*xdlz, Hm, Hmbar);
  double R = Rate(H0, Hp, Hm, _cosH, _chi);
  double Rbar = Rate(H0bar, Hpbar, Hmbar, _cosH, _chi);

  _Rsum = 0.5*(R+Rbar)* effphsp;
  _RInterf = InterfRate(H0, Hp, Hm, H0bar, Hpbar, Hmbar, _cosH, _chi)
      *effphsp *TComplex(cos(-1.0*_phis),sin(-1.0*_phis)) ;
      
  //std::cout << "_Rsum _Rdif _RInterf " << _Rsum << " " << _Rdif << " " << _RInterf << std::endl;
  delete xdlz;
}

//new Integration
/*
void RooDalitzBS::DPTermsIntegralNew() const
{
  CalCoupling();
}
*/

void RooDalitzBS::DPTermsIntegral() const
{
  CalCoupling();
// if(1) {
  if(checkchange()) {
//    std::cout << "Changed " << std::endl;
    DPTermsIntegralMethod1();
  } else {
    int nr = _resList->GetSize();
    
    double hx = (dlz_hx-dlz_lx)/2./np_dlzx;
    double hy = (dlz_hy-dlz_ly)/2./(np_dlzy);
  
    double RsumInt(0);
    TComplex RInterfInt = TComplex(0);
    for(int ir1=0; ir1<nr; ++ir1) {
      for(int ir2=0; ir2<nr; ++ir2) {
        for(int ih=0; ih<3; ++ih) {
          RsumInt += (0.5*HH[ih][ir1][ir2]*
                          (HHR[ir1][ih]*TComplex::Conjugate(HHR[ir2][ih])
                           +HHRbar[ir1][ih]*TComplex::Conjugate(HHRbar[ir2][ih]))).Re();  
          RInterfInt +=  HH[ih][ir1][ir2] * HHRbar[ir1][ih]*TComplex::Conjugate(HHR[ir2][ih]);   
        }
        RsumInt += (0.5*HH[3][ir1][ir2]*
                        (HHR[ir1][2]*TComplex::Conjugate(HHR[ir2][0])
                         +HHRbar[ir1][2]*TComplex::Conjugate(HHRbar[ir2][0]))).Re();  
        RInterfInt +=  0.5*HH[3][ir1][ir2] *HHRbar[ir1][2]*TComplex::Conjugate(HHR[ir2][0])
          +0.5*TComplex::Conjugate(HH[3][ir1][ir2]*HHR[ir1][2]*TComplex::Conjugate(HHRbar[ir2][0]));
        //HH[3][ir1][ir2])*HHRbar[ir1][0]*TComplex::Conjugate(HHRbar[ir2][2]));
      }
    }
    _RsumInt = RsumInt * hx*hy;
    _RInterfInt = RInterfInt *hx*hy*TComplex(cos(-1.0*_phis),sin(-1.0*_phis));
    
  }
  
 //update cached resparam
  int ir(0);
  TIterator* coefIter=_resList->MakeIterator();
  while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
    RooArgList ires = (*Ires);
    int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();
    double m0 = 0;
    double g0 = 0;
    double rg = 0;

    if(type==1) { //breit wigner
      m0 = ((RooAbsReal&)ires[ires.getSize()-4]).getVal();
      g0 = ((RooAbsReal&)ires[ires.getSize()-3]).getVal();
    } else if(type==2) { //f0 flatte
      m0 = ((RooAbsReal&)ires[2]).getVal();
      g0 = ((RooAbsReal&)ires[3]).getVal();
      rg = ((RooAbsReal&)ires[4]).getVal();
    } else if(type==10) {//spline
//       std::cout << "SP par" << std::endl;
       for(int it3=0; it3<ires.getSize(); ++it3) {
          _resSpnCache[it3] = ((RooAbsReal&)ires[it3]).getVal();
//          std::cout << _resSpnCache[it3] << std::endl;
       }
    }
    _resParCache[3*ir+0] = m0;
    _resParCache[3*ir+1] = g0;
    _resParCache[3*ir+2] = rg;
    ir++;
  }
  delete coefIter;
}

//Integration of m(hh) and coshh; already integral over chi and cosH in RateIntegral
void RooDalitzBS::DPTermsIntegralMethod1() const
{
  //TComplex HH[4][MYRN][MYRN];
  int nr = _resList->GetSize();
  for(int ir1=0; ir1<nr; ++ir1) {
    for(int ir2=0; ir2<nr; ++ir2) {
      for(int ih=0; ih<4; ++ih){
        HH[ih][ir1][ir2] = 0.0;
      }
    }  
  }
  double hx = (dlz_hx-dlz_lx)/2./np_dlzx;
  double hy = (dlz_hy-dlz_ly)/2./(np_dlzy);
  
  int ng = pdlz->size();
  double RsumInt = 0;
  TComplex RInterfInt = TComplex(0);
  TComplex AAbarstar;
  
  double R, Rbar;
  for(int ig = 0; ig<ng; ++ig) {
    Jpsihh_dlz &p = *(*pdlz)[ig];
//    Jpsihh_dlz p = pdlz[ig];
    TComplex H0(0), Hp(0), Hm(0);
    TComplex H0bar(0), Hpbar(0), Hmbar(0);
    amplitude(0,p, H0, H0bar);
    amplitude(1,p, Hp, Hpbar);
    amplitude(-1,p, Hm, Hmbar);
//    if(ig==0) printf("\n check cached pdlz %10.6f %10.6f",  p.dre[0][1], p.dre[1][1]);
    R = RateIntegral(H0, Hp, Hm, p);
    Rbar = RateIntegral(H0bar, Hpbar, Hmbar, p);
    AAbarstar = InterfRateIntegral(H0,Hp,Hm,H0bar,Hpbar, Hmbar, p);
    /*
    
    double xeff = 1.0;
//  if(p.mpp<1.2) xeff = 0.0;
    if(p.mpp>dlz_hy) xeff *= hr;
    double effphsp = pR*pB*xeff;
    */
    double effphsp = p.phsp;
    RsumInt += 0.5*(R+Rbar)*effphsp;
    RInterfInt += AAbarstar*effphsp;  

    for(int ir1=0; ir1<nr; ++ir1) {
      for(int ir2=0; ir2<nr; ++ir2) {
        for(int ih=0; ih<=2; ++ih) {
          int iI = 1;
          if(ih==1) iI = 0;
          HH[ih][ir1][ir2] += effphsp*TComplex(p.dre[ir1][ih],p.dim[ir1][ih]) *
            TComplex::Conjugate(TComplex(p.dre[ir2][ih],p.dim[ir2][ih])) * p.Inte[iI];
        }
      }  
    }
    for(int ir1=0; ir1<nr; ++ir1) {
      for(int ir2=0; ir2<nr; ++ir2) {
        int iI = 2;
        HH[3][ir1][ir2] += effphsp*TComplex(p.dre[ir1][2],p.dim[ir1][2]) *
          TComplex::Conjugate(TComplex(p.dre[ir2][0],p.dim[ir2][0])) * p.Inte[iI];
      }
    }  
  }
 
  
  _RsumInt = RsumInt * hx*hy;
  _RInterfInt = RInterfInt *hx*hy*TComplex(cos(-1.0*_phis),sin(-1.0*_phis));
  
 
}

void RooDalitzBS::getInt(double *v0int, double *vlint, double *veint, Bool_t force, double ylo, double yhi) const
{
  int nres = _resList->GetSize();
  double a0[21],al[21],ae[21];
  double A0[21],Al[21],Ae[21];
  for(int i=0; i<21; ++i) {
    a0[i] = 0;
    al[i] = 0;
    ae[i] = 0;
    A0[i] = 0;
    Al[i] = 0;
    Ae[i] = 0;
  }
  
  double hx = (dlz_hx-dlz_lx)/2./np_dlzx;
  double hy = (dlz_hy-dlz_ly)/2./(np_dlzy);
  
  int ng = pdlz->size();
  CalCoupling(); 
  for(int ig = 0; ig<ng; ++ig) {
    Jpsihh_dlz &p = *(*pdlz)[ig];
    if(!(p.mpp>ylo&&p.mpp<yhi)) continue;
    Amplitude(0,p, &a0[0], force);
    Amplitude(1,p, &al[0], force);
    Amplitude(-1,p, &ae[0], force);

    double pB = getpB(p.mpp);
    double pR = getpR(p.mpp);
    
    double xeff = 1.0;
        
//    xeff = efficiency(p.mpp,p.cospp);
/*  double m2pp = p.mpp*p.mpp;
    Double_t I1 = effcosHIntegral(m2pp, 1);
    Double_t I2 = effcosHIntegral(m2pp, 2);
*/
    double effphsp = pR*pB*xeff;
  
    for(int i=0; i<=nres; ++i) {
      A0[i] += a0[i]*effphsp;//*I1;
      Al[i] += al[i]*effphsp;//*I2;
      Ae[i] += ae[i]*effphsp;//*I2;
    }
  }
  
  double sum = A0[0]+Al[0]+Ae[0];  
//  std::cout<<< "sum int " << sum << std::endl;
  for(int k=1; k<=nres;++k) {
      v0int[k-1] = A0[k]/sum;
      vlint[k-1] = Al[k]/sum;
      veint[k-1] = Ae[k]/sum;
  }
  
}

void RooDalitzBS::getIntf(double *v0int, double *vlint, double *veint, Bool_t force, double ylo, double yhi) const
{
  int nres = _resList->GetSize();
  int ninf = nres*(nres-1)/2;
  
  double a0[55],al[55],ae[55];
  double A0[55],Al[55],Ae[55];
  for(int i=0; i<55; ++i) {
    a0[i] = 0;
    al[i] = 0;
    ae[i] = 0;
    A0[i] = 0;
    Al[i] = 0;
    Ae[i] = 0;
  }
    CalCoupling(); 
  double hx = (dlz_hx-dlz_lx)/2./np_dlzx;
  double hy = (dlz_hy-dlz_ly)/2./(np_dlzy);
  
  int ng = pdlz->size();
 
  for(int ig = 0; ig<ng; ++ig) {
    Jpsihh_dlz &p = *(*pdlz)[ig];
    if(!(p.mpp>ylo&&p.mpp<yhi)) continue;
    Interfer(0,p, &a0[0], force);
    Interfer(1,p, &al[0], force);
    Interfer(-1,p, &ae[0], force);

    double pB = getpB(p.mpp);
    double pR = getpR(p.mpp);
    
    double xeff = 1.0;
        
//    xeff = efficiency(p.mpp,p.cospp);
/*  double m2pp = p.mpp*p.mpp;
    Double_t I1 = effcosHIntegral(m2pp, 1);
    Double_t I2 = effcosHIntegral(m2pp, 2);
*/
    double effphsp = pR*pB*xeff;
  
    for(int i=0; i<=ninf; ++i) {
      A0[i] += a0[i]*effphsp;//*I1;
      Al[i] += al[i]*effphsp;//*I2;
      Ae[i] += ae[i]*effphsp;//*I2;
    }
  }
  
  double sum = A0[0]+Al[0]+Ae[0];  
  //std::cout<<< "sum int " << sum << std::endl;  
  for(int k=1; k<=ninf;++k) {
      v0int[k-1] = A0[k]/sum;
      vlint[k-1] = Al[k]/sum;
      veint[k-1] = Ae[k]/sum;
  }
  
}


//replace function in RooAbsAnaConvPdf by adding DP calcuations
//_____________________________________________________________________________
Double_t RooDalitzBS::evaluate() const
{
  double inttt(-1);
  if(_norm) inttt = _norm->getVal();
  DPTerms();//_Rsum, _Rdif, _RInterf);
//  std::cout << "ev " << _Rsum - _dgover2g*_RInterf.Re() << std::endl;
  return _Rsum - _dgover2g*_RInterf.Re();
}

///////////////////////////////////////////////////////////////////////
//
//                 Event generation 
//
//////////////////////////////////////////////////////////////////////
/*
Int_t RooDalitzBS::getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK) const {
  // Advertize own event generator.
  std::cout<<"=============================================================="<<std::endl;
  std::cout<<GetName()<<": Requested generation of these variables:"<<std::endl;
  directVars.Print("V");
  std::cout<<"=============================================================="<<std::endl<<std::endl;
 
  
  RooArgSet List1;
  List1.add(*(_chi.absArg()));
  List1.add(*(_cosH.absArg()));
  List1.add(*(_coshh.absArg()));
  List1.add(*(_mhh.absArg()));
  if (matchArgs(directVars,generateVars, List1)) return 4; 

  std::cout <<"Not matched"<<std::endl;
  return 0 ;
}

void RooDalitzBS::initGenerator(Int_t code) {
  // assert(code==2);
  if (*_pdfmax>0) return;
  // sample Dalitz space to find the highest pdf  
  *_pdfmax=-1;
  int nsample=0;
  while (nsample++<20000) {
    Double_t pdftmp = sampleEvent();
    if (pdftmp>*_pdfmax) *_pdfmax=pdftmp;
  }
  *_pdfmax*=1.05; // increase 5% for safety
  std::cout << " pdfmax = " << (*_pdfmax) << std::endl;
}


Double_t RooDalitzBS::sampleEvent() {
  // Sample a uniform distribution with exponential. return a possible max pdf/exp(gammamin)
  double vrnd[3];
  RooRandom::uniform(3, vrnd);
  _coshh = (_coshh.max()-_coshh.min())*vrnd[0]+_coshh.min();
  _chi = (_chi.max()-_chi.min())*vrnd[1]+_chi.min();
  _cosH = (_cosH.max()-_cosH.min())*vrnd[2]+_cosH.min();
  while(1) {
    double vrnd3 = RooRandom::uniform();
    _mhh = (_mhh.max()-_mhh.min())*vrnd3+_mhh.min();
    if(kine_limits(_mhh))   break;
  }
  return evaluate();
}


void RooDalitzBS::generateEvent(Int_t code) 
{
  // Generate event. 
  //std::cout << "generation code " << code << std::endl;
  //  assert(code==2);
//  sampleEvent();
//  std::cout << "generation " << _t << " " << _mhh << " " << _coshh << " " << _cosH << " " << _chi << std::endl;
//  return;
  while(1) {
    Double_t f = sampleEvent();
    if((*_pdfmax)*RooRandom::uniform() > f) continue;
    break;
  }
//  std::cout << "generation " << _t << " " << _mhh << " " << _coshh << " " << _cosH << " " << _chi << std::endl;
}
*/
Double_t RooDalitzBS::evaluate(
	Double_t xmhh, 
	Double_t xcoshh, 
	Double_t xcosH, 
	Double_t xchi )
{
  _mhh = xmhh;
  _coshh = xcoshh;
  _cosH = xcosH;
  _chi = xchi;

  return evaluate();
}
  

