/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODALITZTIMECP3TAG
#define ROODALITZTIMECP3TAG

#include "RooAbsAnaConvPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooDalitzAmplitude.h"
#include "RooRealVar.h"
 
//class Jpsihh_dlz;

/* class Jpsihh_dlz { */
/* public: */
/*   double cospp; */
/*   double mpp; */
/*   double dre[10][3]; */
/*   double dim[10][3]; */
/*   Jpsihh_dlz() {} */

/* private: */
/*   ClassDef(Jpsihh_dlz, 1); */
/* }; */

class RooDalitzTimeCP3Tag : public RooAbsAnaConvPdf, public RooDalitzAmplitude  {
public:
  enum DecayType { SingleSided, DoubleSided, Flipped };
  //inline RooDalitzTimeCP3Tag() {} ; 
  RooDalitzTimeCP3Tag(const char *name, const char *title,
		      RooRealVar& t,
		      RooAbsReal& mhh, //m(hh)
		      RooAbsReal& coshh, //cos(hh)
		      RooAbsReal& cosH, //cos(jpsi)
		      RooAbsReal& chi, //chi angle
		      RooAbsCategory& tag, RooAbsReal& avgMistag,
		      RooRealVar &efftag,
		      RooArgList Calibtag, RooArgList delMistag, 
		      RooAbsReal& tau, RooAbsReal& dgamma, RooAbsReal& dm, 
		      RooRealVar& beta, TList *resList, RooArgList peff, 
		      RooArgList pcosH, RooArgList pchi,
		      const RooResolutionModel &resModel,
		      DecayType type=SingleSided);
  RooDalitzTimeCP3Tag(const RooDalitzTimeCP3Tag& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDalitzTimeCP3Tag(*this,newname); }
  virtual ~RooDalitzTimeCP3Tag() { }
  
  virtual Double_t coefficient(Int_t basisIndex) const;
  virtual Int_t getCoefAnalyticalIntegral(Int_t coef, RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  virtual Double_t coefAnalyticalIntegral(Int_t coef, Int_t code, const char* rangeName=0) const ;

  Int_t getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK=kTRUE) const;
  void initGenerator(Int_t code);  
  void generateEvent(Int_t code);
  Double_t sampleEvent();
//  void setAcccosHFlat();
  void getInt(double *v0int, double *vlint, double* veint, double ylo=0, double yhi=3.0) const;  
  Double_t evaluate(Double_t xt, Double_t xmhh, Double_t xcoshh, 
		    Double_t xcosH, Double_t xchi, Int_t xtag);
  
protected:

  RooRealProxy _t ;
  RooRealProxy _mhh ; 
  RooRealProxy _coshh ;
  RooRealProxy _cosH; //cosTheta_Jpsi
  RooRealProxy _chi; // angle Chi
  RooCategoryProxy _tag ;
  RooRealProxy _avgMistag ;
  RooListProxy _delMistag;
  RooListProxy _Calibtag;
  RooRealProxy _efftag;
  RooRealProxy _tau ;
  RooRealProxy _dgamma ;
  RooRealProxy _dm ;
  RooRealProxy _phis;
  DecayType _type;
  RooListProxy _resParams ;
  RooListProxy _peff;
  RooListProxy _pcosH;
  RooListProxy _pchi;
  
  Int_t _basisCosh;
  Int_t _basisSinh;
  Int_t _basisCos;
  Int_t _basisSin;
  mutable Double_t _Rsum;
  mutable Double_t _Rdif;
  mutable TComplex _RInterf;

  mutable Double_t _RsumInt;
  mutable Double_t _RdifInt;
  mutable TComplex _RInterfInt;
  mutable bool _redoInt;
  Double_t *_pdfmax;

  void DPTerms() const;//Double_t &Rsum, Double_t &Rdif, TComplex &RInterf);
  void DPTermsIntegral() const;//Double_t &RsumInt, Double_t & RdifInt, TComplex &RInterfInt) const;
  Double_t evaluate() const;

private:
  Double_t tageff() const;
  Double_t DTag() const;
  Double_t MisTag() const;
  // ClassDef(RooDalitzTimeCP3Tag,1) // Your description goes here...
};
 
#endif
