/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "RooFit.h"
#include "Riostream.h" 
#include "RooDalitzTimeCPCBTAG.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooRandom.h"
//#include "Jpsihh_dlz.h"

//ClassImp(RooDalitzTimeCPCBTAG) 

//#define F2CON 1
#ifdef F2CON
extern double FFF2;
#endif


RooDalitzTimeCPCBTAG::RooDalitzTimeCPCBTAG(const char *name, const char *title,
	RooRealVar& t,
	RooAbsReal& mhh,   //m(hh)
	RooAbsReal& coshh, //cos(hh)
	RooAbsReal& cosH,  //cos(jpsi)
	RooAbsReal& chi,   //chi angle
	TH2F & etapdf,
	RooAbsCategory& tag1, RooAbsReal& eta1,
	RooAbsCategory& tag2, RooAbsReal& eta2, 
	RooArgList efftag, RooAbsReal &defftag,
	RooArgList Calibtag, RooArgList dCalibtag, 
	RooAbsReal& tau, RooAbsReal& dgamma, 
	RooAbsReal& dm, 
	TList *cpList, TList *resList, 
	TList *effList,
	double ML, double MR,					      
	const RooResolutionModel &resModel,
	DecayType dtype,
	double FFR,
	double FFB):
   RooAbsAnaConvPdf(name,title, resModel, t), 
   RooDalitzAmplitude(resList, cpList, effList, ML, MR, FFR, FFB),
   _t("t","t",this,t),
   _mhh("mhh","invariant mass pipi",this,mhh),
   _coshh("coshh","cos(theta_hh)",this,coshh),
   _cosH("cosH","cos(Helicity of J/psi", this, cosH),
   _chi("chi","angle of two decay planes", this, chi),
   _etapdf(etapdf),
   _tag1("tag1","Tag state1",this,tag1),
   _eta1("eta1","mistag ratio1",this,eta1),
   _tag2("tag2","Tag state2",this,tag2),
   _eta2("eta2","mistag ratio2",this,eta2),
   _dCalibtag("dCalibtag", "list of #DeltaMistag", this),
   _Calibtag("Calibtag", "list of calib parameters", this),
   _efftag("efftag", "tag eff", this),
   _RP("defftag", "Produce Ratio BBar/B", this, defftag),  
   _tau("tau","tau",this,tau),
   _dgamma("dgamma","dgamma",this,dgamma),
   _dm("dm","dm",this,dm),
   _dtype(dtype),
   _resParams("resParams", "Parameters for resonaces", this),
   _cpParams("cpParams", "Parameters for CP violation", this),  
   _Rsum(0),  _Rdif(0),  _RInterf(0),
   _RsumInt(0),  _RdifInt(0),  _RInterfInt(0),
   _redoInt(1)
{ 
   _dCalibtag.add(dCalibtag);
   _Calibtag.add(Calibtag);
   _efftag.add(efftag);
   //Constructor
   int ir(0);
   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList *Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	RooArgList icp = *(RooArgList*)(_cpList->At(ir));
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();
	//     std::cout << "type " << type << std::endl;
	//     std::cout  << type << std::endl;
	ir++;
	//    if (type!=1&&type!=2&&type!=3&&type!=4) continue;
	_cpParams.add(icp[0]);
	_cpParams.add(icp[1]);  

	if(type==1) { //breit wigner
	   _resParams.add(ires[0]);
	   _resParams.add(ires[1]);
	   _resParams.add(ires[2]);
	   _resParams.add(ires[3]);
	   int Spin = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
	   if(Spin>0) {
		_resParams.add(ires[4]);
		_resParams.add(ires[5]);
		_resParams.add(ires[6]);
		_resParams.add(ires[7]);
		_cpParams.add(icp[2]);
		_cpParams.add(icp[3]);
		_cpParams.add(icp[4]);
		_cpParams.add(icp[5]);
	   }
	} else if(type==2) { //f0 flatte
	   _resParams.add(ires[0]);
	   _resParams.add(ires[1]);
	   _resParams.add(ires[2]);
	   _resParams.add(ires[3]);      
	   _resParams.add(ires[4]);        
	} else if(type==3||type==4||type==5) { //noresonace
	   _resParams.add(ires[0]);
	   _resParams.add(ires[1]);
	} else if(type==10) { //Spline
	   for(int i=0; i<ires.getSize()-1; ++i) _resParams.add(ires[i]);
	   MakeSpline(ires);
	}
   }
   delete coefIter;

   switch(dtype)
   {
	case SingleSided:
	   _basisCosh = declareBasis("exp(-@0/@1)*cosh(@0*@2/2)", RooArgList(tau,dgamma));
	   _basisSinh = declareBasis("exp(-@0/@1)*sinh(@0*@2/2)", RooArgList(tau,dgamma));
	   _basisCos = declareBasis("exp(-@0/@1)*cos(@0*@2)",RooArgList(tau, dm));
	   _basisSin = declareBasis("exp(-@0/@1)*sin(@0*@2)",RooArgList(tau, dm));
	   break;
	case Flipped:
	   _basisCosh = declareBasis("exp(@0/@1)*cosh(@0*@2/2)", RooArgList(tau,dgamma));
	   _basisSinh = declareBasis("exp(@0/@1)*sinh(@0*@2/2)", RooArgList(tau,dgamma));
	   _basisCos = declareBasis("exp(@0/@1)*cos(@0*@2)",RooArgList(tau, dm));
	   _basisSin = declareBasis("exp(@0/@1)*sin(@0*@2)",RooArgList(tau, dm));
	   break;
	case DoubleSided:
	   _basisCosh = declareBasis("exp(-abs(@0)/@1)*cosh(@0*@2/2)", RooArgList(tau,dgamma));
	   _basisSinh = declareBasis("exp(-abs(@0)/@1)*sinh(@0*@2/2)", RooArgList(tau,dgamma));
	   _basisCos = declareBasis("exp(-abs(@0)/@1)*cos(@0*@2)",RooArgList(tau, dm));
	   _basisSin = declareBasis("exp(-abs(@0)/@1)*sin(@0*@2)",RooArgList(tau, dm));
	   break;
   }
   _pdfmax = new Double_t; *_pdfmax = -1;
   CalCoupling();
   std::cout << " Calculate DPTermsIntegral " << std::endl;
   DPTermsIntegralMethod1();
   //  cout << "DPTermsIntegral " << _RsumInt << " " <<  _RdifInt << " " <<  _RInterfInt.Re() << " " << _RInterfInt.Im() << endl;
}


RooDalitzTimeCPCBTAG::RooDalitzTimeCPCBTAG(const RooDalitzTimeCPCBTAG& other, const char* name) :  
   RooAbsAnaConvPdf(other,name), 
   RooDalitzAmplitude(other),
   _t("t",this,other._t),
   _mhh("mhh",this,other._mhh),
   _coshh("coshh",this,other._coshh),
   _cosH("cosH",this,other._cosH),
   _chi("chi",this, other._chi),
   _etapdf(other._etapdf),
   _tag1("tag1",this,other._tag1),
   _eta1("eta1",this,other._eta1),
   _tag2("tag2",this,other._tag2),
   _eta2("eta2",this,other._eta2),
   _dCalibtag("dCalibtag", this, other._dCalibtag),
   _Calibtag("Calibtag", this, other._Calibtag),
   _efftag("efftag", this, other._efftag),
   _RP("defftag", this, other._RP),  
   _tau("tau",this,other._tau),
   _dgamma("dgamma",this,other._dgamma),
   _dm("dm",this,other._dm),
   _dtype(other._dtype),
   _resParams("resParams", this, other._resParams),
   _cpParams("cpParams", this, other._cpParams), 
   _basisCosh(other._basisCosh),
   _basisSinh(other._basisSinh),
   _basisCos(other._basisCos),
   _basisSin(other._basisSin),
   _Rsum(other._Rsum),
   _Rdif(other._Rdif),
   _RInterf(other._RInterf),
   _RsumInt(other._RsumInt),
   _RdifInt(other._Rdif),
   _RInterfInt(other._RInterfInt),
   HH(other.HH),
   _redoInt(other._redoInt)
{ 
   //Copy constructor
   //  _isPHSPGen = other._isPHSPGen;
   _pdfmax = other._pdfmax;
} 

void RooDalitzTimeCPCBTAG::CombineTag() const
{
   if( _tag1==0 && _tag2==0 ){
	_tag = 0;
	_avgMistag = 0.5;
	_delMistag = 0.0;
   } 
   if( _tag1!=0 && _tag2 == 0 ){
	_tag = _tag1;
	_avgMistag = MisTag(1);
	_delMistag = delMisTag(1);
   }
   if( _tag1==0 && _tag2 != 0 ){
	_tag = _tag2;
	_avgMistag = MisTag(2);
	_delMistag = delMisTag(2);
   }
   if( _tag1*_tag2 != 0 ){
	double mistag1 = MisTag(1);
	double mistag2 = MisTag(2);
	double dw1 = delMisTag(1);
	double dw2 = delMisTag(2);
	double wp1 = mistag1 +dw1/2.;
	double wp2 = mistag2 +dw2/2.;
	double wm1 = mistag1 -dw1/2.;
	double wm2 = mistag2 -dw2/2.;
	
	double cbwp,cbwm;

	if( _tag1 == _tag2 ){
	   _tag = _tag1;
	   cbwp = wp1*wp2/(wp1*wp2+(1.-wp1)*(1.-wp2));
	   cbwm = wm1*wm2/(wm1*wm2+(1.-wm1)*(1.-wm2));      

	}else{
	   if( mistag1 < mistag2 ){
		_tag = _tag1;
		cbwp = wp1*(1.-wp2)/(wp1*(1.-wp2)+(1.-wp1)*wp2);
		cbwm = wm1*(1.-wm2)/(wm1*(1.-wm2)+(1.-wm1)*wm2);
	   }else{
		_tag = _tag2;
		cbwp = wp2*(1.-wp1)/(wp1*(1.-wp2)+(1.-wp1)*wp2);
		cbwm = wm2*(1.-wm1)/(wm1*(1.-wm2)+(1.-wm1)*wm2);
	   }

	}
	_avgMistag = (cbwp+cbwm)/2.;
	_delMistag = cbwp-cbwm;      
   }

}


Double_t RooDalitzTimeCPCBTAG::MisTag(int itag) const
{
   double mistag(0.5);
   if(itag == 1) mistag = _eta1;
   else if(itag == 2) mistag = _eta2;
   else {return mistag;}
   if( (itag==1&&_tag1==0)||(itag==2&&_tag2==0) ) return mistag;

   //do calibration
   double p0, p1, etac;
   p0   = ( (RooAbsReal&)_Calibtag[(itag-1)*3]   ).getVal();
   p1   = ( (RooAbsReal&)_Calibtag[(itag-1)*3+1] ).getVal();
   etac = ( (RooAbsReal&)_Calibtag[(itag-1)*3+2] ).getVal();

   double mistag_c = p0+p1*(mistag-etac);
   //if(mistag_c>0.5) mistag_c = 0.5; // keep it ?

   return mistag_c;
}


Double_t RooDalitzTimeCPCBTAG::delMisTag(int itag) const
{
   double mistag(0.5);
   if(itag == 1) mistag = _eta1;
   else if(itag == 2) mistag = _eta2;

   //if(mistag<0.001 || mistag>=0.5) return 0.0;
   if( (itag==1&&_tag1==0)||(itag==2&&_tag2==0) ) return 0.0;

   //do calibration
   double dp0, dp1, etac;
   dp0  = ( (RooAbsReal&)_dCalibtag[(itag-1)*2]   ).getVal();
   dp1  = ( (RooAbsReal&)_dCalibtag[(itag-1)*2+1] ).getVal();
   etac = ( (RooAbsReal&)_Calibtag[(itag-1)*3+2]  ).getVal();

   double mistag_c =  dp0+dp1*(mistag-etac);
   return mistag_c;
}

Double_t RooDalitzTimeCPCBTAG::tageff() const
{
   double teff(0);
   int ios = (int)(_eta1/0.05)+1;
   int iss = (int)(_eta2/0.05)+1; 

   if(_tag1!=0&&_tag2!=0) { //Both
	teff = ((RooAbsReal&)_efftag[0]).getVal();
	//teff *= _etapdf.GetBinContent(ios,1)*_etapdf.GetBinContent(iss,2);
   } else if(_tag1!=0&&_tag2==0) { //OS only
	teff = ((RooAbsReal&)_efftag[1]).getVal();
	//teff *= _etapdf.GetBinContent(ios,1);
   } else if(_tag1==0&&_tag2!=0) { //SS only
	teff = ((RooAbsReal&)_efftag[2]).getVal();
	//teff *= _etapdf.GetBinContent(iss,2);
   } else {
	teff = 1.0-((RooAbsReal&)_efftag[0]).getVal()-((RooAbsReal&)_efftag[1]).getVal()-((RooAbsReal&)_efftag[2]).getVal();
   }

   if(teff<1e-10) std::cout << "tagging eff " << teff << std::endl;
   return teff;
}

//_____________________________________________________________________________
Double_t RooDalitzTimeCPCBTAG::coefficient(Int_t basisIndex) const
{
   // B0    : _tag = +1 
   // B0bar : _tag = -1 

   CombineTag();
   double as = (1.0+_tag*(1.-2.*(_avgMistag+_delMistag/2.)))+_RP*(1.0-_tag*(1.-2.*(_avgMistag-_delMistag/2.)));
   double ad = (1.0+_tag*(1.-2.*(_avgMistag+_delMistag/2.)))-_RP*(1.0-_tag*(1.-2.*(_avgMistag-_delMistag/2.)));

   if( basisIndex == _basisCosh )      return  tageff()*as*_Rsum/2.0;             
   else if( basisIndex == _basisSinh ) return -1.0*tageff()*as*_RInterf.Re()/2.0; 
   else if( basisIndex == _basisCos  ) return  tageff()*ad*_Rdif/2.0;             
   else if( basisIndex == _basisSin  ) return -1.0*tageff()*ad*_RInterf.Im()/2.0; 

   return 0 ;
}

//_____________________________________________________________________________
Int_t RooDalitzTimeCPCBTAG::getCoefAnalyticalIntegral(Int_t /*code*/, RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const 
{
   // Advertize existance of own integration over the Dalitz plot.

   //std::cout<<"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"<<std::endl;
   //std::cout<<"Requested integration over these variables: "<<std::endl;
   //allVars.Print("V");
   //std::cout<<"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"<<std::endl;

   RooArgSet List;
   List.add(*(_chi.absArg()));
   List.add(*(_cosH.absArg()));
   List.add(*(_coshh.absArg()));
   List.add(*(_mhh.absArg()));
   List.add(*(_tag1.absArg()));
   List.add(*(_eta1.absArg()));
   List.add(*(_tag2.absArg()));
   List.add(*(_eta2.absArg()));
   if( matchArgs(allVars, analVars, List) )  return 6;

   RooArgSet List1;
   List1.add(*(_chi.absArg()));
   List1.add(*(_cosH.absArg()));
   List1.add(*(_coshh.absArg()));
   List1.add(*(_mhh.absArg()));
   List1.add(*(_tag1.absArg()));
   List1.add(*(_tag2.absArg()));
   if( matchArgs(allVars, analVars, List1) )  return 5;
   if( matchArgs(allVars, analVars, _mhh, _coshh, _cosH, _chi) )  return 2;
   if( matchArgs(allVars, analVars, _tag1, _tag2) ) return 1;

   return 0 ;
}

Double_t RooDalitzTimeCPCBTAG::coefAnalyticalIntegral(Int_t basisIndex, Int_t code, const char* rangeName) const 
{
   double NormFactor(1);
   double as,ad;
   //  cout << "Integral code " << code << endl;
   switch(code) {

	case 0: // No integration
	   return coefficient(basisIndex);

	case 1: // Integration over 'tag'
	   if(basisIndex==_basisCosh)      { DPTerms(); return _Rsum*(1.0+_RP)/2.0; }
	   else if(basisIndex==_basisSinh) { DPTerms(); return -_RInterf.Re()*(1.0+_RP)/2.0;}
	   else if(basisIndex==_basisCos) return (1.0-_RP)*_Rdif/2.0;   
	   else if(basisIndex==_basisSin) return -(1.0-_RP)*_RInterf.Im()/2.0;
	   else assert(0);

	case 2: // Integration over mass, coshel
	   CombineTag();
	   as = (1.0+_tag*(1.-2.*(_avgMistag+_delMistag/2.)))+_RP*(1.0-_tag*(1.-2.*(_avgMistag-_delMistag/2.)));
	   ad = (1.0+_tag*(1.-2.*(_avgMistag+_delMistag/2.)))-_RP*(1.0-_tag*(1.-2.*(_avgMistag-_delMistag/2.)));

	   if(basisIndex == _basisCosh)        return  tageff()*as*_RsumInt/2.0;        // tageff()*(1.-_tag*_delMistag)*_Rsum;
	   else if(basisIndex == _basisSinh)   return -tageff()*as*_RInterfInt.Re()/2.0;//-tageff()*(1.-_tag*_delMistag)*_RInterf.Re();
	   else if(basisIndex == _basisCos)    return  tageff()*ad*_RdifInt/2.0;        //(1.0-2.*_avgMistag)*tageff()*_tag*_Rdif;
	   else if(basisIndex == _basisSin)    return -1.0*tageff()*ad*_RInterfInt.Im()/2.0;    
	   else assert(0);

	case 5: // Integration over 'tag', mass, coshel
	   if( basisIndex==_basisCosh ){
		DPTermsIntegral(); 
		_redoInt = false; 
		//      std::cout <<  std::endl;
		//      std::cout << " calculate DP Integral " << _RsumInt ;
		return _RsumInt*(1.0+_RP)/2.0;
	   }else if( basisIndex==_basisSinh ){
		if(_redoInt) DPTermsIntegral(); 
		return -_RInterfInt.Re()*(1.0+_RP)/2.0;

	   }else if( basisIndex==_basisCos ){
		return (1.0-_RP)*_RdifInt/2.0;

	   }else if( basisIndex==_basisSin ){
		_redoInt = true; 
		return -(1.0-_RP)*_RInterfInt.Im()/2.0;

	   }else{ assert(0); }

	case 6: // Integration over 'tag', mass, coshel, mistag
	   NormFactor = (_eta1.max(rangeName)-_eta1.min(rangeName))*(_eta2.max(rangeName)-_eta2.min(rangeName));
	   if( basisIndex==_basisCosh ){
		DPTermsIntegral(); 
		_redoInt = false; 
		return NormFactor*_RsumInt*(1.0+_RP)/2.0;

	   }else if( basisIndex==_basisSinh ){
		if(_redoInt) DPTermsIntegral(); 
		return -NormFactor*_RInterfInt.Re()*(1.0+_RP)/2.0;

	   }else if( basisIndex==_basisCos ){
		return NormFactor*(1.0-_RP)*_RdifInt/2.0;

	   }else if( basisIndex==_basisSin ){
		_redoInt = true; 
		return -NormFactor*(1.0-_RP)*_RInterfInt.Im()/2.0;

	   }else{ assert(0); }

	default: assert(0);

   }

   return 0;
}


///////////////////////////////////////////////////////////////////////
//
//                  Total PDF
//
//////////////////////////////////////////////////////////////////////
void RooDalitzTimeCPCBTAG::DPTerms() const//Double_t &Rsum, Double_t &Rdif, TComplex &RInterf) {
{
   // Evaluate |A|^2 +/- |Abar|^2 term in the B0-B0bar time-evolution equation. 
   _Rsum = 0;
   _Rdif = 0;
   _RInterf = TComplex(0);

   //double Rsum(0), Rdif(0);
   //TComplex RInterf(0);
   if(!kine_limits(_mhh))   return;
   if(fabs(_cosH)>1||fabs(_coshh)>1) return;  
   double m2pp = _mhh*_mhh;
   double xeff = efficiency(_mhh,_coshh,_cosH,_chi);//efficiency(_mhh,_coshh)*effcosH(m2pp, _cosH)*effchi(m2pp,_chi);
   double pB = getpB(_mhh);
   double pR = getpR(_mhh);
   double effphsp = pR*pB*xeff;

   Jpsihh_dlz *xdlz = new Jpsihh_dlz();
   //cout << "_Rsum _Rdif _RInterf " << _Rsum << " " << _Rdif << " " << _RInterf << endl;
   filldlz(*xdlz, _mhh, _coshh);
   TComplex H0(0), Hp(0), Hm(0);
   TComplex H0bar(0), Hpbar(0), Hmbar(0);
   amplitude(0,*xdlz, H0, H0bar);
   amplitude(1,*xdlz, Hp, Hpbar);
   amplitude(-1,*xdlz, Hm, Hmbar);
   double R = Rate(H0, Hp, Hm, _cosH, _chi);
   double Rbar = Rate(H0bar, Hpbar, Hmbar, _cosH, _chi);

   _Rsum = 0.5*(R+Rbar)* effphsp;
   _Rdif = 0.5*(R-Rbar)* effphsp;
   _RInterf = InterfRate(H0, Hp, Hm, H0bar, Hpbar, Hmbar, _cosH, _chi) * effphsp ; 
   //cout << "_Rsum _Rdif _RInterf " << _Rsum << " " << _Rdif << " " << _RInterf << endl;
   delete xdlz;
}

void RooDalitzTimeCPCBTAG::PrintDPInt()
{
   DPTermsIntegral();
   std::cout << "DPTermsIntegral " << _RsumInt << " " <<  _RdifInt << " " <<  _RInterfInt.Re() << " " << _RInterfInt.Im() << std::endl;
}

//Integration of m(hh) and coshh; already integral over chi and cosH in RateIntegral
void RooDalitzTimeCPCBTAG::DPTermsIntegralMethod1() const
{

   int nr = _resList->GetSize();
   for(int ir1=0; ir1<nr; ++ir1) {
	for(int ir2=0; ir2<nr; ++ir2) {
	   for(int ih=0; ih<4; ++ih) {//helicity
		HH[ih][ir1][ir2] = 0.0;
	   }
	}
   }
   double hx = (dlz_hx-dlz_lx)/2./np_dlzx;
   double hy = (dlz_hy-dlz_ly)/2./np_dlzy;
   // double hy1 = (dlz_hy-dlz_y_cut)/2./(np_dlzy*0.8);
   //double hr = hy1/hy;

   int ng = pdlz->size();
   double RsumInt = 0;
   double RdifInt = 0;
   double R,Rbar;
   TComplex RInterfInt = TComplex(0);
   TComplex AAbarstar;
   for(int ig = 0; ig<ng; ++ig) {
	Jpsihh_dlz &p = *(*pdlz)[ig];
	//Jpsihh_dlz p = pdlz[ig];
	TComplex H0(0), Hp(0), Hm(0);
	TComplex H0bar(0), Hpbar(0), Hmbar(0);
	amplitude(0,p, H0, H0bar);
	amplitude(1,p, Hp, Hpbar);
	amplitude(-1,p, Hm, Hmbar);
	//    if(ig==0) printf("\n check cached pdlz %10.6f %10.6f",  p.dre[0][1], p.dre[1][1]);
	R = RateIntegral(H0, Hp, Hm, p);
	Rbar = RateIntegral(H0bar, Hpbar, Hmbar, p);
	AAbarstar = InterfRateIntegral(H0,Hp,Hm,H0bar,Hpbar, Hmbar, p);
	/*
	   double pB = getpB(p.mpp);
	   double pR = getpR(p.mpp);

	   double xeff = 1.0;
	   double effphsp = pR*pB*xeff;
	   */
	double effphsp = p.phsp;
	RsumInt += 0.5*(R+Rbar)*effphsp;
	RdifInt += 0.5*(R-Rbar)*effphsp;
	RInterfInt += AAbarstar*effphsp;
	for(int ir1=0; ir1<nr; ++ir1) {
	   for(int ir2=0; ir2<nr; ++ir2) {
		for(int ih=0; ih<=2; ++ih) {
		   int iI = 1;
		   if(ih==1) iI = 0;
		   HH[ih][ir1][ir2] += effphsp*TComplex(p.dre[ir1][ih],p.dim[ir1][ih]) *
			TComplex::Conjugate(TComplex(p.dre[ir2][ih],p.dim[ir2][ih])) * p.Inte[iI];
		}
	   }  
	}
	for(int ir1=0; ir1<nr; ++ir1) {
	   for(int ir2=0; ir2<nr; ++ir2) {
		int iI = 2;
		HH[3][ir1][ir2] += effphsp*TComplex(p.dre[ir1][2],p.dim[ir1][2]) *
		   TComplex::Conjugate(TComplex(p.dre[ir2][0],p.dim[ir2][0])) * p.Inte[iI];
	   }
	}  
   }
   _RsumInt = RsumInt * hx*hy;
   _RdifInt = RdifInt * hx*hy;
   _RInterfInt = RInterfInt *hx*hy;
   //cout<<" ----------------------------"<<endl;
   //cout<<"  Check of integral. "<<endl;
   //cout<<" ----------------------------"<<endl;

}


//Integration of m(hh) and coshh; already integral over chi and cosH in RateIntegral
void RooDalitzTimeCPCBTAG::DPTermsIntegral() const
{
   CalCoupling();
   if(checkchange()) {
	DPTermsIntegralMethod1();
   } else {
	int nr = _resList->GetSize();
	double hx = (dlz_hx-dlz_lx)/2./np_dlzx;
	double hy = (dlz_hy-dlz_ly)/2./(np_dlzy);
	double RsumInt = 0;
	double RdifInt = 0;
	TComplex RInterfInt = TComplex(0);
	for(int ir1=0; ir1<nr; ++ir1) {
	   for(int ir2=0; ir2<nr; ++ir2) {
		for(int ih=0; ih<3; ++ih) {
		   RsumInt += (0.5*HH[ih][ir1][ir2]*
			   (HHR[ir1][ih]*TComplex::Conjugate(HHR[ir2][ih])
			    +HHRbar[ir1][ih]*TComplex::Conjugate(HHRbar[ir2][ih]))).Re();
		   RdifInt += (0.5*HH[ih][ir1][ir2]*
			   (HHR[ir1][ih]*TComplex::Conjugate(HHR[ir2][ih])
			    -HHRbar[ir1][ih]*TComplex::Conjugate(HHRbar[ir2][ih]))).Re();   
		   RInterfInt +=  HH[ih][ir1][ir2] * HHRbar[ir1][ih]*TComplex::Conjugate(HHR[ir2][ih]);   
		}
		RsumInt += (0.5*HH[3][ir1][ir2]*
			(HHR[ir1][2]*TComplex::Conjugate(HHR[ir2][0])
			 +HHRbar[ir1][2]*TComplex::Conjugate(HHRbar[ir2][0]))).Re();  
		RdifInt += (0.5*HH[3][ir1][ir2]*
			(HHR[ir1][2]*TComplex::Conjugate(HHR[ir2][0])
			 -HHRbar[ir1][2]*TComplex::Conjugate(HHRbar[ir2][0]))).Re();  
		RInterfInt +=  0.5*HH[3][ir1][ir2] *HHRbar[ir1][2]*TComplex::Conjugate(HHR[ir2][0])
		   +0.5*TComplex::Conjugate(HH[3][ir1][ir2]*HHR[ir1][2]*TComplex::Conjugate(HHRbar[ir2][0]));
		//HH[3][ir1][ir2])*HHRbar[ir1][0]*TComplex::Conjugate(HHRbar[ir2][2]));
	   }
	}
	_RsumInt = RsumInt * hx*hy;
	_RdifInt = RdifInt * hx*hy;
	_RInterfInt = RInterfInt *hx*hy;
   }
   //if constraint f2' do this calculation: f2' is the second resonance.

#ifdef F2CON
   double v0int[21], vlint[21], veint[21];
   getInt(v0int, vlint, veint);
   FFF2 = (v0int[1]+vlint[1]+veint[1]);
   //  std::cout << "FFF2" << FFF2 << std::endl;
#endif

   //update cached resparam
   int ir(0);
   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();
	double m0 = 0;
	double g0 = 0;
	double rg = 0;

	if(type==1) { //breit wigner
	   m0 = ((RooAbsReal&)ires[ires.getSize()-4]).getVal();
	   g0 = ((RooAbsReal&)ires[ires.getSize()-3]).getVal();
	} else if(type==2) { //f0 flatte
	   m0 = ((RooAbsReal&)ires[2]).getVal();
	   g0 = ((RooAbsReal&)ires[3]).getVal();
	   rg = ((RooAbsReal&)ires[4]).getVal();
	} else if(type==10) {
	   for(int it3=0; it3<ires.getSize(); ++it3) {
		_resSpnCache[it3] = ((RooAbsReal&)ires[it3]).getVal();
		//          std::cout << _resSpnCache[it3] << std::endl;
	   }
	}
	_resParCache[3*ir+0] = m0;
	_resParCache[3*ir+1] = g0;
	_resParCache[3*ir+2] = rg;
	ir++;
   }
   delete coefIter;

}



void RooDalitzTimeCPCBTAG::getInt(double *v0int, double *vlint, double *veint, Bool_t force, double ylo, double yhi) const
{
   int nres = _resList->GetSize();
   double a0[21],al[21],ae[21];
   double A0[21],Al[21],Ae[21];
   for(int i=0; i<21; ++i) {
	a0[i] = 0;
	al[i] = 0;
	ae[i] = 0;
	A0[i] = 0;
	Al[i] = 0;
	Ae[i] = 0;
   }

   double hx = (dlz_hx-dlz_lx)/2./np_dlzx;
   double hy = (dlz_hy-dlz_ly)/2./(np_dlzy);

   int ng = pdlz->size();

   for(int ig = 0; ig<ng; ++ig) {
	Jpsihh_dlz &p = *(*pdlz)[ig];
	if(!(p.mpp>ylo&&p.mpp<yhi)) continue;
	Amplitude(0,p, &a0[0], force);
	Amplitude(1,p, &al[0], force);
	Amplitude(-1,p, &ae[0], force);

	double pB = getpB(p.mpp);
	double pR = getpR(p.mpp);

	double xeff = 1.0;

	//    xeff = efficiency(p.mpp,p.cospp);
	/*  double m2pp = p.mpp*p.mpp;
	    Double_t I1 = effcosHIntegral(m2pp, 1);
	    Double_t I2 = effcosHIntegral(m2pp, 2);
	    */
	double effphsp = pR*pB*xeff;

	for(int i=0; i<=nres; ++i) {
	   A0[i] += a0[i]*effphsp;//*I1;
	   Al[i] += al[i]*effphsp;//*I2;
	   Ae[i] += ae[i]*effphsp;//*I2;
	}
   }

   double sum = A0[0]+Al[0]+Ae[0];  
   //  std::cout<<< "sum int " << sum << std::endl;
   for(int k=1; k<=nres;++k) {
	v0int[k-1] = A0[k]/sum;
	vlint[k-1] = Al[k]/sum;
	veint[k-1] = Ae[k]/sum;
   }

}

Double_t RooDalitzTimeCPCBTAG::ModT(Double_t xt, Double_t xmhh,
	Double_t xcoshh,
	Double_t xcosH, Double_t xchi)
{
   _t = xt;
   _mhh = xmhh;
   _coshh = xcoshh;
   _cosH = xcosH;
   _chi = xchi;

   DPTerms();
   double C = _Rdif;
   double S = _RInterf.Im();
   //ASY = S*sin(dt)-C*cos(dt)
   double norm = sqrt(C*C+S*S);
   if(norm<1e-10) return xt;
   C = C/norm; S = S/norm;
   double delta = TMath::ATan2(C,S);
   double tm = _dm * _t - delta;
   tm = fmod(tm, 2.*TMath::Pi());
   if(tm<0) tm += 2.*TMath::Pi();
   return tm/_dm;
}

Int_t RooDalitzTimeCPCBTAG::GetTagDec(Int_t tag1, Double_t wtag1,
	Int_t tag2, Double_t wtag2,
	Double_t &wtag)
{
   wtag = 0.5;
   if(tag1==0&&tag2==0) return 0;
   _tag1 = tag1;
   _tag2 = tag2;

   _eta1 = wtag1;
   _eta2 = wtag2;
   CombineTag();
   if((1.-2.*_avgMistag)>1e-10) {wtag = _avgMistag; return _tag;}
   else if(fabs(1.-2.*_avgMistag)<1e-10) {wtag = 0.5; return 0;}
   else {wtag = 1.-_avgMistag; return -1*_tag;}

}

//-----------------------------------------------------------------
//replace function in RooAbsAnaConvPdf by adding DP calcuations
//-----------------------------------------------------------------
Double_t RooDalitzTimeCPCBTAG::evaluate() const
{
   // Calculate the current unnormalized value of the PDF
   //
   // PDF = sum_k coef_k * [ basis_k (x) ResModel ]
   //

   double inttt(-1);
   if(_norm) inttt = _norm->getVal();

   Double_t result(0) ;
   //added DP calcuations

   DPTerms();//_Rsum, _Rdif, _RInterf);
   //  _convSetIter->Reset() ;
   //  RooAbsPdf* conv ;
   //  std::cout << "_avgMistag " << _avgMistag << std::endl;

   Int_t index(0) ;
   for (auto convArg : _convSet) {
	auto conv = static_cast<RooAbsPdf*>(convArg);
	//while(((conv=(RooAbsPdf*)_convSetIter->Next()))) {
	Double_t coef = coefficient(index++) ;
	if (coef!=0.) {
	   Double_t c = conv->getVal(0) ;
	   Double_t r = coef ;
	   cxcoutD(Eval) << "RooAbsAnaConvPdf::evaluate(" << GetName() << ") val += coef*conv [" << index-1 << "/" 
		<< _convSet.getSize() << "] coef = " << r << " conv = " << c << std::endl ;
	   result += conv->getVal(0)*coef ;
	} else {
	   cxcoutD(Eval) << "RooAbsAnaConvPdf::evaluate(" << GetName() << ") [" << index-1 << "/" << _convSet.getSize() << "] coef = 0" << std::endl ;
	}
   }
   //  if(result<=0) cout << "evaluate " << result << " " << _mhh << " " << _t <<  endl;
   return result;

}

Double_t RooDalitzTimeCPCBTAG::evaluate(
	Double_t xt, Double_t xmhh, Double_t xcoshh,
	Double_t xcosH, Double_t xchi, Int_t xtag)
{  

   _chi = xchi;
   _cosH = xcosH;
   _coshh = xcoshh;
   _mhh = xmhh;
   _tag1 = xtag;
   _t = xt;
   _tag2 = 0;
   _eta1 = 0;
   _eta2 = 0.5;
   CalCoupling();

   //double _eval =  evaluate();
   //if( _eval < 1e-10 ) _eval = 0;
   //return _eval;
   return evaluate();
}


///////////////////////////////////////////////////////////////////////
//
//                 Event generation 
//
//////////////////////////////////////////////////////////////////////
Int_t RooDalitzTimeCPCBTAG::getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK) const {
   // Advertize own event generator.
   cout<<"=============================================================="<<endl;
   cout<<GetName()<<": Requested generation of these variables:"<<endl;
   directVars.Print("V");
   cout<<"=============================================================="<<endl<<endl;

   RooArgSet List4;
   List4.add(*(_chi.absArg()));
   List4.add(*(_cosH.absArg()));
   List4.add(*(_coshh.absArg()));
   List4.add(*(_mhh.absArg()));
   List4.add(*(_tag1.absArg()));  
   List4.add(*(_tag2.absArg()));  
   List4.add(*(_t.absArg()));
   List4.add(*(_eta1.absArg()));
   List4.add(*(_eta2.absArg()));	    
   if (matchArgs(directVars,generateVars, List4)) return 52; 

   RooArgSet List3;
   List3.add(*(_chi.absArg()));
   List3.add(*(_cosH.absArg()));
   List3.add(*(_coshh.absArg()));
   List3.add(*(_mhh.absArg()));
   List3.add(*(_tag1.absArg()));  
   List3.add(*(_tag2.absArg()));  
   List3.add(*(_t.absArg()));
   if (matchArgs(directVars,generateVars, List3)) return 51; 

   RooArgSet List;
   List.add(*(_chi.absArg()));
   List.add(*(_cosH.absArg()));
   List.add(*(_coshh.absArg()));
   List.add(*(_mhh.absArg()));
   List.add(*(_t.absArg()));
   if (matchArgs(directVars,generateVars, List)) return 5;

   //RooArgSet List2;
   //List2.add(*(_chi.absArg()));
   //List2.add(*(_cosH.absArg()));
   //List2.add(*(_coshh.absArg()));
   //List2.add(*(_mhh.absArg()));
   //List2.add(*(_tag.absArg()));  
   //if (matchArgs(directVars,generateVars, List2)) return 41; 

   RooArgSet List1;
   List1.add(*(_chi.absArg()));
   List1.add(*(_cosH.absArg()));
   List1.add(*(_coshh.absArg()));
   List1.add(*(_mhh.absArg()));
   if (matchArgs(directVars,generateVars, List1)) return 4; 

   if (matchArgs(directVars,generateVars, _t)) return 1;
   std::cout <<"Not matched"<<std::endl;
   return 0 ;
}

void RooDalitzTimeCPCBTAG::initGenerator(Int_t code) {
   // assert(code==2);
   if (*_pdfmax>0) return;
   // sample Dalitz space to find the highest pdf  
   *_pdfmax=-1;
   int nsample=0;
   while (nsample++<20000) {
	Double_t pdftmp = sampleEvent();
	if (pdftmp>*_pdfmax) *_pdfmax=pdftmp;
   }
	*_pdfmax*=1.15; // increase 5% for safety
	//  cout << " pdfmax = " << (*_pdfmax) << endl;
}


Double_t RooDalitzTimeCPCBTAG::sampleEvent() {
   // Sample a uniform distribution with exponential. return a possible max pdf/exp(gammamin)
   double vrnd[3];
   RooRandom::uniform(3, vrnd);
   _coshh = (_coshh.max()-_coshh.min())*vrnd[0]+_coshh.min();
   _chi = (_chi.max()-_chi.min())*vrnd[1]+_chi.min();
   _cosH = (_cosH.max()-_cosH.min())*vrnd[2]+_cosH.min();
   while(1) {
	double vrnd3 = RooRandom::uniform();
	_mhh = (_MR-_ML)*vrnd3+_ML;//(_mhh.max()-_mhh.min())*vrnd3+_mhh.min();
	if(kine_limits(_mhh)) {
	   if(_mhh<1.05) {
		break; 
	   } else {
		if(RooRandom::uniform()<0.025) {  //for >1.05 factor 0.025 scale : two ladder MC
		   break;
		}
	   }
	}
   }
   DPTerms();
   //(_f0*cosh(dgt)+_f1*sinh(dgt)+_f2*cos(dmt)+_f3*sin(dmt));
   double f0 = _Rsum ; 
   double f1 = -1.0*_RInterf.Re();
   double f2 = _Rdif; 
   double f3 =  -1.0*_RInterf.Im();
   //return maximum
   double max= TMath::Abs(f0)+TMath::Abs(f1)+sqrt(f2*f2+f3*f3);
   if(_mhh<1.05) max *= 0.025;
   return max;
}


void RooDalitzTimeCPCBTAG::generateEvent(Int_t code) 
{
   // Generate event. 
   //! Alert don't generate avgMistag. use avgMistag as pre-input
   //  cout << "generation code " << code << endl;
   //  assert(code==2);
   //  sampleEvent();
   //  cout << "generation " << _t << " " << _mhh << " " << _coshh << " " << _cosH << " " << _chi << endl;
   //  return;

   //cout<<" code type : "<< code<<endl;
   if(code==52) {
	double w1, w2;
	double rnd = RooRandom::uniform();
	double effbo = ((RooAbsReal&)_efftag[0]).getVal();
	double effos = ((RooAbsReal&)_efftag[1]).getVal();
	double effss = ((RooAbsReal&)_efftag[2]).getVal();
	int tagcat = 0;
	if(rnd<effos) { tagcat = 1; } //OS
	else if(rnd<effos+effss) { tagcat = 2;} //SS
	else if(rnd<effos+effss+effbo) { tagcat = 3; } //BO
	w2 = 0.5;
	w1 = 0.5;
	if(tagcat==1||tagcat==3) w1 = ((TH1D*)_etapdf.ProjectionX("pos",1,1))->GetRandom();
	if(tagcat==2||tagcat==3) w2 = ((TH1D*)_etapdf.ProjectionX("pss",2,2))->GetRandom();
	//if(tagcat==2||tagcat==3) w2 = ((TH1D*)_etapdf.ProjectionX("pss",1,1))->GetRandom();
	if(w2>=0.5) w2=0.5;
	if(w1>=0.5) w1=0.5;
	_eta1 = w1;
	_eta2 = w2;    
   }
   
   Double_t gammamin = 1/_tau-TMath::Abs(_dgamma)/2;
   while(1) {
	Double_t t = _t;
	if(code!=4&&code!=41) {
	   t = -log(RooRandom::uniform())/gammamin;
	   if (_dtype == Flipped || (_dtype == DoubleSided && RooRandom::uniform() <0.5) ) t *= -1;
	   if ( t<_t.min() || t>_t.max() ) continue;
	}

	if(code==51||code==52) {
	   _tag1 = 0;
	   _tag2 = 0;
	   if(_eta1-0.5<-1e-10) { 
		if(RooRandom::uniform()<0.5) {
		   _tag1 = 1;
		} else {
		   _tag1 = -1;
		}
	   }
	   if(_eta2-0.5<-1e-10) { 
		if(RooRandom::uniform()<0.5) {
		   _tag2 = 1;
		} else {
		   _tag2 = -1;
		}
	   }
	   if( (_tag1 == 0 && _eta1<0.5)||(_tag2 == 0 && _eta2<0.5) ){ cout<<" wrong tagged : "<<_tag1<<" "<<_tag2<<" "<<_eta1<<" "<<_eta2<<endl; }
	}
	Double_t dgt = _dgamma*t/2;
	Double_t dmt = _dm*t;
	Double_t ft = fabs(t);
	
	//not work for code=1;
	if(code!=1) sampleEvent();

	double f0 = coefficient(_basisCosh); 
	double f1 = coefficient(_basisSinh);
	double f2 = coefficient(_basisCos);
	double f3 = coefficient(_basisSin);    
	Double_t f = exp(-ft/_tau)*(f0*cosh(dgt)+f1*sinh(dgt)+f2*cos(dmt)+f3*sin(dmt));
	if(f < 0) {
	   std::cout << "RooDalitzTimeCPCBTAG::generateEvent(" << GetName() << ") ERROR: PDF value less than zero" << std::endl;
	   ::abort();
	}
	if(_mhh<1.05) f *= 0.025;
	Double_t w = exp(-ft*gammamin)*(*_pdfmax)*tageff();
	//    if(_tag==0) cout << "check max" << f/w << endl;
	if(w < f) {
	   // cout << "RooDalitzTimeCPCBTAG::generateEvent(" << GetName() << ") ERROR: Envelope function less than p.d.f. " << endl;
	   // cout << f0 << endl;
	   // cout << f1 << endl;
	   // cout << f2 << endl;
	   // cout << f3 << endl;
	   ::abort();
	}
	if(w*RooRandom::uniform() > f) continue;
	_t = t;
	break;
   }

}


