/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODALITZBS
#define ROODALITZBS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooDalitzAmplitude.h"
#include "RooRealVar.h"
 
//class Jpsihh_dlz;

/* class Jpsihh_dlz { */
/* public: */
/*   double cospp; */
/*   double mpp; */
/*   double dre[10][3]; */
/*   double dim[10][3]; */
/*   Jpsihh_dlz() {} */

/* private: */
/*   ClassDef(Jpsihh_dlz, 1); */
/* }; */

class RooDalitzBS : public RooAbsPdf, public RooDalitzAmplitude  {
public:
  //inline RooDalitzBS() {} ; 
  RooDalitzBS(
	  const char *name, 
	  const char *title,
	  RooAbsReal& mhh, //m(hh)
	  RooAbsReal& coshh, //cos(hh)
	  RooAbsReal& cosH,  //cos(jpsi)
	  RooAbsReal& chi,   //chi angle
	  RooAbsReal& , 
	  RooRealVar& ,
	  TList *resList, 
	  TList *, 
	  TList *, 
	  double FFR=1.5, double FFB=5.0
	  );

  RooDalitzBS(const RooDalitzBS& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDalitzBS(*this,newname); }
  virtual ~RooDalitzBS() { }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

  // Int_t getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK=kTRUE) const;
  // void initGenerator(Int_t code);  
  // void generateEvent(Int_t code);
  // Double_t sampleEvent();
  // void setAcccosHFlat();
  void getInt(double *v0int, double *vlint, double* veint, Bool_t force=0, double ylo=0, double yhi=3.0) const;  
  void getIntf(double *v0int, double *vlint, double* veint, Bool_t force=0, double ylo=0, double yhi=3.0) const;    
  Double_t evaluate(double, double, double, double);  

  void setPhspRes( int isPhsp );
protected:

  RooRealProxy _mhh; 
  RooRealProxy _coshh;
  RooRealProxy _cosH; //cosTheta_Jpsi
  RooRealProxy _chi; // angle Chi
  RooRealProxy _dgover2g;
  RooRealProxy _phis;  
  RooListProxy _resParams;
  RooListProxy _cpParams;

  mutable Double_t _Rsum;
  mutable Double_t _RsumInt;
  mutable TComplex _RInterf;
  mutable TComplex _RInterfInt;
  mutable TComplex HH[4][MYRN][MYRN];
  mutable bool _redoInt;
  Double_t *_pdfmax;

  void DPTerms() const;//Double_t &Rsum, Double_t &Rdif, TComplex &RInterf);
  void DPTermsIntegral() const;//Double_t &RsumInt, Double_t & RdifInt, TComplex &RInterfInt) const;
  void DPTermsIntegralMethod1() const;
  Double_t evaluate() const;
  double NormalEff();

private:
  //Double_t tageff() const;
  // ClassDef(RooDalitzBS,1) // Your description goes here...
};

#endif
