/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPHICONSTNEW
#define ROOPHICONSTNEW

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPhiConstNew : public RooAbsReal {
public:
  RooPhiConstNew() {} ; 
  RooPhiConstNew(const char *name, const char *title,
	      RooAbsReal& ,
	      RooAbsReal& ,
	      RooAbsReal &,
	      RooAbsReal& ,
	      RooAbsReal &,	      
	      double *,
	      double *,
	      double *);
  RooPhiConstNew(const RooPhiConstNew& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPhiConstNew(*this,newname); }
  inline virtual ~RooPhiConstNew() { }

protected:

  RooRealProxy G ;
  RooRealProxy dg ;
  RooRealProxy phis ;
  RooRealProxy lambda ;  
  RooRealProxy dms ;  

  double *aclm;
  double *err;
  double *x0;
  Double_t evaluate() const ;

private:

  //ClassDef(RooPhiConstNew,1) // Your description goes here...
};
 
#endif
