/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPHIGDG
#define ROOPHIGDG

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPhiGDG : public RooAbsReal {
public:
  RooPhiGDG() {} ; 
  RooPhiGDG(const char *name, const char *title,
	      RooAbsReal& _G,
	      RooAbsReal& _dg);
  RooPhiGDG(const RooPhiGDG& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPhiGDG(*this,newname); }
  inline virtual ~RooPhiGDG() { }

protected:

  RooRealProxy G ;
  RooRealProxy dg ;
  
  Double_t evaluate() const ;

private:

  //ClassDef(RooPhiGDG,1) // Your description goes here...
};
 
#endif
