/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 
/*----------------------------Description of the PDF-------------------------
 * This is PDF class for Bs->J/psi Pi Pi Dalitz Plot Fit.
 * It uses 2 invariant masses to describe the amplitude.
 * For signal Amplitude we have used,
 * A(m12,m13) = equation (2) of Physical Review D 78, 072004 (2008)
 * and hence the signal PDF S(m12, m13) = a_i*exp(-i*phi)*A(m12,m13)
 * Total amplitude is based on PLB 719 (2013) 383
 *****************************************************************************/

#include "Riostream.h" 
#include "RooDalitzAmplitude.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

#include "TIterator.h"
#define PDG

//#define fitphi
//ClassImp(RooDalitzAmplitude) 
//for perpendicular component, the lowest LB is +1 than the others;
//int aLB(0);

int _exlKsRange = 0;
double _mKs_l = 0.465;
double _mKs_h = 0.505;

RooDalitzAmplitude::RooDalitzAmplitude( TList *resList,
	TList *cpList,
	TList *effList,
	double ML,
	double MR,
	double FFR,
	double FFB) : 
   _resList(resList), _cpList(cpList), _effList(effList),
   np_dlzx(50), np_dlzy(500), dlz_hx(1), dlz_lx(-1),
   _ML(ML), _MR(MR),
   _iflat(1),_FFR(FFR),_FFB(FFB),_myKm()
{ 
   //m_bs = 5.36688;
   m_bs = 5.27965;
   m_pi = 0.13957061;
   m_jpsi = 3.096900;
   //m_pi = 0.493677;
   m2_bs = m_bs*m_bs;
   m2_pi = m_pi*m_pi;
   m2_jpsi = m_jpsi*m_jpsi;

   dlz_ly = 2*m_pi;
   dlz_hy = m_bs-m_jpsi;

   int nres = _resList->GetSize();
   std::cout << " Number of Resonances : " << nres << std::endl;
   //each set to 3 parms.
   int ncached = 3*nres;
   _resParCache = new Double_t[ncached];
   for (int i=0; i<ncached; i++) _resParCache[i]=0; 
   _resSpnCache = new Double_t[3*NSP];
   for (int i=0; i<3*NSP; i++) _resSpnCache[i]=0;    

   assert(nres<=MYRN); 

   for(int i=0; i<nres; ++i) {
	for(int ih=0; ih<3; ++ih) {
	   HHR[i][ih] = TComplex(0.0,0.0);
	   HHRbar[i][ih] = TComplex(0.0,0.0);
	}
   }
   pdlz = std::make_shared<std::vector<Jpsihh_dlz*>>();

   double hx = (dlz_hx-dlz_lx)/2./(np_dlzx);
   double hy = (dlz_hy-dlz_ly)/2./(np_dlzy);
   //  int sum = 0;
   for(int i=0; i<2*np_dlzx; ++i) {  
	for(int j=0; j<2*(np_dlzy); ++j) {
	   Jpsihh_dlz *p = new Jpsihh_dlz();
	   p->cospp = dlz_lx+i*hx+0.5*hx;
	   // cout << p.cospp << endl;
	   p->mpp = dlz_ly+j*hy+0.5*hy;
	   if(kine_limits(p->mpp)) {
		for(int ir=0; ir<nres; ++ir) {
		   for(int ih=0; ih<3; ++ih) {
			p->dre[ir][ih] = 0.0;
			p->dim[ir][ih] = 0.0;
		   }
		}
		p->Inte[0]=0.0; p->Inte[1]=0.0; p->Inte[2]=0.0;
		double pB = getpB(p->mpp);
		double pR = getpR(p->mpp);
		double xeff = 1.0;
		double effphsp = pR*pB*xeff;        
		p->phsp =effphsp;
		if(p->mpp>=ML&&p->mpp<MR)  pdlz->push_back(p);
		//	sum++;
	   }
	}
   }
   //reset FFR and FFB to PDG value
   //  _FFR = 3.0;
   //  _FFB = 3.0;
   _isPHSPGen = false;
   _myKm.SetValues();
   std::cout << " Integration grids " << pdlz->size()  <<std::endl;     
   //  std::cout << "eff. para. " << ((RooAbsReal&)peff_[0]).getVal() << endl;
}


RooDalitzAmplitude::RooDalitzAmplitude(const RooDalitzAmplitude& other) :  
   _resList(other._resList),
   _cpList(other._cpList),
   _effList(other._effList),
   np_dlzx(other.np_dlzx),np_dlzy(other.np_dlzy),
   dlz_hx(other.dlz_hx), dlz_lx(other.dlz_lx),
   dlz_hy(other.dlz_hy), dlz_ly(other.dlz_ly),
   _ML(other._ML), _MR(other._MR),
   _isPHSPGen(other._isPHSPGen),
   pdlz(other.pdlz), 
   HHR(other.HHR), HHRbar(other.HHRbar),  
   m_bs(other.m_bs),
   m2_bs(other.m2_bs), m_pi(other.m_pi),
   m2_pi(other.m2_pi), m_jpsi(other.m_jpsi),
   m2_jpsi(other.m2_jpsi),_iflat(other._iflat),
   _FFR(other._FFR), _FFB(other._FFB),_myKm(other._myKm),
   _sa3(other._sa3),_sp3(other._sp3)
{
   int n= pdlz->size();
   std::cout << "new pdlz size " << n << std::endl;
   //for(int i=0; i<n; ++i) {
   //      if(pdlz[i].good) {std::cout << "good..." << std::endl; break;}
   //}
   _resParCache = other._resParCache;
   _resSpnCache = other._resSpnCache;

   //  std::cout << "called " << std::endl;
} 

//resList Should have the aruments like 
//res(a-i, delta_i, m0, gamma0, spin, helicity, type of resonance)
/////////////////////////////////////////////////////
//          Total PDF
/////////////////////////////////////////////////////

void RooDalitzAmplitude::setACCcosHFlat()
{
   _iflat = 0;
   //  cout << " called ? " << _iflat << endl;
}

void RooDalitzAmplitude::setFFR(double a)
{
   _FFR = a;
}

void RooDalitzAmplitude::setFFB(double a)
{
   _FFB = a;
}

Bool_t RooDalitzAmplitude::kine_limits(double mpp) const
{
   if(mpp<2*m_pi) return false;
   if(mpp>m_bs-m_jpsi) return false;
   return true;
}

Bool_t RooDalitzAmplitude::kine_limits(double m2kp, double m2pp) const
{
   //   Return 1 if masses are in allowed kinematic region for Dalitz plot
   double m2km;
   double mkp,mpp,mkm;
   double p2m, p2p, p2k;
   double ep_star, em_star;
   double pp_star, pm_star, e_sum2;
   double m2pp_min, m2pp_max;

   //  m2kp = (double) m_12;
   //  m2pp = (double) m_13;
   //  m2km = (double) m_13;

   m2km = m2_bs - m2kp - m2pp + 2*m2_pi + m2_jpsi;

   if(m2pp<0) return false;
   mkp = sqrt(m2kp);
   mkm = sqrt(m2km);
   mpp = sqrt(m2pp);

   p2m = 1./4./m2_bs*(m2_bs-pow(mkp+m_pi,2))*(m2_bs-pow(mkp-m_pi,2));
   p2p = 1./4./m2_bs*(m2_bs-pow(mkm+m_pi,2))*(m2_bs-pow(mkm-m_pi,2));
   p2k = 1./4./m2_bs*(m2_bs-pow(mpp+m_jpsi,2))*(m2_bs-pow(mpp-m_jpsi,2));

   ep_star=(m2kp-m2_jpsi+m2_pi)/2./mkp;
   em_star=(m2_bs-m2kp-m2_pi)/2./mkp;
   if(ep_star<m_pi || em_star< m_pi) return false;

   pp_star= sqrt(pow(ep_star,2)-m2_pi);
   pm_star= sqrt(pow(em_star,2)-m2_pi);
   e_sum2 = pow(ep_star+em_star,2);
   m2pp_max = e_sum2-pow(pp_star-pm_star,2);
   m2pp_min = e_sum2-pow(pp_star+pm_star,2);

   if (m2pp<m2pp_min || m2pp>m2pp_max) return false;
   if (p2m>0&&p2p>0&&p2k>0) return true;
   return false;
}

//convert coshh to m(Jpsih+)
Double_t RooDalitzAmplitude::getM2Jpsih(double mpp, double cospp) const 
{
   double SDP  = m2_bs + 2*m2_pi + m2_jpsi;
   double m2pp = mpp*mpp;
   double pB = getpB(mpp);
   double pR = getpR(mpp);
   return 0.5*(SDP-m2pp)+2.0*pR*pB*m_bs*cospp/mpp;
} 

Double_t RooDalitzAmplitude::LegPol(double x, int i) const
{
   if(i==0) return 1;
   if(i==1) return x;
   if(i==2) return 0.5*(3.*x*x-1);
   if(i==3) return 0.5*(5.*pow(x,3)-3.*x);
   if(i==4) return (35.*pow(x,4)-30*x*x+3)/8.;
   if(i==5) return (63.*pow(x,5)-70.*x*x*x+15*x)/8.;
   if(i==6) return (231.*pow(x,6)-315.*pow(x,4)+105*x*x-5)/16.;
   if(i==7) return (429.*pow(x,7)-693.*pow(x,5)+315.*pow(x,3)-35*x)/16.;
   if(i==8) return (6435.*pow(x,8)-12012.*pow(x,6)+6930.*pow(x,4)-1260*x*x+35.)/128.;
   if(i==10) return 1./256.*(46189.*pow(x,10)-109395.*pow(x,8)+90090.*pow(x,6)-30030.*pow(x,4)+3465*x*x-63);
   if(i==12) return 1./1024.*(231. - 18018.*pow(x,2) + 225225.*pow(x,4) - 1021020.*pow(x,6) + 2078505.*pow(x,8) - 
	   1939938.*pow(x,10) + 676039.*pow(x,12));
   if(i==14) return 1./2048.*(-429. + 45045.*pow(x,2) - 765765.*pow(x,4) + 4849845.*pow(x,6) - 
	   14549535.*pow(x,8) + 22309287.*pow(x,10) - 16900975.*pow(x,12) + 
	   5014575.*pow(x,14));
   if(i==16) return 1./32768.*(6435. - 875160.*pow(x,2) + 19399380.*pow(x,4) - 162954792.*pow(x,6) + 
	   669278610.*pow(x,8) - 1487285800.*pow(x,10) + 1825305300.*pow(x,12) - 
	   1163381400.*pow(x,14) + 300540195.*pow(x,16));          
   if(i==18) return 1./65536.*(-12155. + 2078505.*pow(x,2) - 58198140.*pow(x,4) + 624660036.*pow(x,6) - 
	   3346393050.*pow(x,8) + 10039179150.*pow(x,10) - 17644617900.*pow(x,12) + 
	   18032411700.*pow(x,14) - 9917826435.*pow(x,16) + 2268783825.*pow(x,18));
   if(i==20) return 1./262144.*(46189. - 9699690.*pow(x,2) + 334639305.*pow(x,4) - 4461857400.*pow(x,6) + 
	   30117537450.*pow(x,8) - 116454478140.*pow(x,10) + 273491577450.*pow(x,12) - 
	   396713057400.*pow(x,14) + 347123925225.*pow(x,16) - 167890003050.*pow(x,18) + 34461632205.*pow(x,20));
   if(i==22) return (-88179. + 22309287*pow(x,2) - 929553625*pow(x,4) + 15058768725*pow(x,6) - 
	   124772655150*pow(x,8) + 601681470390*pow(x,10) - 1805044411170*pow(x,12) + 
	   3471239252250*pow(x,14) - 4281195077775*pow(x,16) + 3273855059475*pow(x,18) - 
	   1412926920405*pow(x,20) + 263012370465*pow(x,22))/524288.;            
   if(i==24) return (676039. - 202811700*pow(x,2) + 10039179150*pow(x,4) - 194090796900*pow(x,6) + 
	   1933976154825*pow(x,8) - 11345993441640*pow(x,10) + 
	   42117702927300*pow(x,12) - 102748681866600*pow(x,14) + 
	   166966608033225*pow(x,16) - 178970743251300*pow(x,18) + 
	   121511715154830*pow(x,20) - 47342226683700*pow(x,22) + 8061900920775*pow(x,24)
	   )/4.194304e6;
   if(i==26) return (-1300075. + 456326325*pow(x,2) - 26466926850*pow(x,4) + 601681470390*pow(x,6) - 
	   7091245901025*pow(x,8) + 49638721307175*pow(x,10) - 
	   222622144044300*pow(x,12) + 667866432132900*pow(x,14) - 
	   1369126185872445*pow(x,16) + 1923935489951475*pow(x,18) - 
	   1822675727322450*pow(x,20) + 1112542327066950*pow(x,22) - 
	   395033145117975*pow(x,24) + 61989816618513*pow(x,26))/8.388608e6;

   return 0;
}

//convert to Real using cos(phi), x 2 for complex ones
Double_t RooDalitzAmplitude::YM(double cosx, double phi, int l, int m) const
{
   double x = cosx;
   double pi = TMath::Pi();
   if(l==0&&m==0) return 0.5/sqrt(pi);
   if(l==1&&m==0) return 0.5*sqrt(3./pi)*x;
   if(l==1&&m==1) return -sqrt(1.5/pi)*sqrt(1-x*x)*cos(phi);
   if(l==2&&m==0) return 0.25*sqrt(5./pi)*(3*x*x-1);
   if(l==2&&m==1) return -sqrt(15./2./pi)*sqrt(1-x*x)*x*cos(phi);
   if(l==2&&m==2) return 0.5*sqrt(15./2./pi)*(1-x*x)*cos(2.*phi);
   if(l==3&&m==1) return -1./4.*sqrt(21./pi)*sqrt(1-x*x)*(5.*x*x-1.)*cos(phi);    
   if(l==4&&m==0) return 3./16./sqrt(pi)*(35.*pow(x,4)-30.*x*x+3.);
   if(l==4&&m==2) return 3./4.*sqrt(2.5/pi)*(1-x*x)*(7.*x*x-1.)*cos(2.*phi); 
   if(l==5&&m==1) return -1./8.*sqrt(165./2./pi)*(1-14*x*x+21*pow(x,4))*sqrt(1-x*x)*cos(phi);
   if(l==6&&m==0) return 1./32.*sqrt(13./pi)*(-5.+105.*x*x-315*pow(x,4)+231*pow(x,6));
   if(l==6&&m==2) return 1./32.*sqrt(1365./pi)*(1-18*x*x+33*pow(x,4))*(1-x*x)*cos(2.*phi);
   if(l==8&&m==0) return 1./256.*sqrt(17./pi)*(35-1260*x*x+6930*pow(x,4)-12012*pow(x,6)+6435*pow(x,8));
   if(l==8&&m==2) return 3./64.*sqrt(595./pi)*(-1+33*x*x-143*pow(x,4)+143*pow(x,6))*(1-x*x)*cos(2.*phi);  

   return 0;
}

Double_t RooDalitzAmplitude::Seff(double xmhh, double xcoshh, double xcosH, double xphi,
	int a, int b, int c, int d, double ra) const
{
   double mmin = 2*m_pi;
   double mmax = m_bs-m_jpsi;

   double norm_m = 2.*(xmhh-mmin)/(mmax-mmin)-1;
   return YM(xcosH,xphi,b,c)*LegPol(xcoshh,a)*LegPol(norm_m,d)*ra;
}

void RooDalitzAmplitude::excludeKsRange( int exlKsRange ){
   _exlKsRange = exlKsRange;
}

void RooDalitzAmplitude::setKsRange( double mKs_l, double mKs_h ){
   _mKs_l = mKs_l;
   _mKs_h = mKs_h;
}

Double_t RooDalitzAmplitude::efficiency(double mpp, double cospp, double cosh, double xchi, bool isphi) const
{
   //if(fabs(mpp-0.489)<0.02) return 0.0;
   //cout<<_mKs_l<<" "<<_mKs_h<<endl;
   if( _exlKsRange == 1 ){
	if( mpp>_mKs_l &&mpp< _mKs_h ){
	   return 0.0;
	}
   }

   if(!kine_limits(mpp)) return 0;
   double sum(0);
   double Norm(1.);
   TList *EffList = _effList;
   TIterator* Iter= EffList->MakeIterator();
   while(RooArgList* Ieff = (RooArgList*)Iter->Next()) {
	RooArgList ieff = (*Ieff);
	int a = (int)((RooAbsReal&)ieff[0]).getVal();
	int b = (int)((RooAbsReal&)ieff[1]).getVal();
	int c = (int)((RooAbsReal&)ieff[2]).getVal();
	int d = (int)((RooAbsReal&)ieff[3]).getVal();
	double coef = ((RooAbsReal&)ieff[4]).getVal();
	//    std::cout << a << " " << b << " " << c << " " << d << " " << coef << std::endl;
	sum += Seff(mpp, cospp, cosh, xchi, a,b,c,d,coef);
   }
   delete Iter;
   sum = sum*Norm;
   if(sum<0) {
	//	std::cout << " efficiency check " << mpp << " "  << cospp << " " << sum << std::endl;
	sum=0;
   }
   return sum;
}


Double_t RooDalitzAmplitude::YMIntegral(int index, int l, int m) const
/*
//considering symmetric acceptance i.e. l+m = 2n, only need to do three integration:
index=1 for sin^2, index=2 for (1+cos^2)/2., index=3 sin^2*cos(2chi)
*/
{
   double pi = TMath::Pi();
   if(l==0&&m==0) {
	if(index==1||index==2) return 4.*sqrt(pi)/3.;
	return 0;
   }
   if(l==2&&m==0) {
	if(index==1) return -4./3.*sqrt(pi/5.);
	if(index==2) return 2./3.*sqrt(pi/5.);
	return 0;
   }
   if(l==2&&m==2) {
	if(index==3) return 4.*sqrt(2.*pi/15.);
	return 0;
   }
   return 0;
}

Double_t RooDalitzAmplitude::effcosHchiIntegral(int index, double xmhh, double xcoshh) const
{

   double mmin= 2*m_pi;
   double mmax = m_bs-m_jpsi;
   double norm_m = 2.*(xmhh-mmin)/(mmax-mmin)-1;
   if(!(index>=1&&index<=3)) {std::cout << "index wrong " << std::endl; return 0;}
   double sum(0);
   TList *EffList = _effList;
   double Norm(1.0);
   TIterator* Iter=EffList->MakeIterator();

   while(RooArgList* Ieff = (RooArgList*)Iter->Next()) {
	RooArgList ieff = (*Ieff);
	int a = (int)((RooAbsReal&)ieff[0]).getVal();
	int b = (int)((RooAbsReal&)ieff[1]).getVal();
	int c = (int)((RooAbsReal&)ieff[2]).getVal();
	int d = (int)((RooAbsReal&)ieff[3]).getVal();
	double coef = ((RooAbsReal&)ieff[4]).getVal();
	sum += coef*YMIntegral(index,b,c)*LegPol(xcoshh,a)*LegPol(norm_m,d);
   }

   delete Iter;
   sum = sum * Norm;
   if(sum<0) {
	//cout << "eff check " << mpp << " " << sum << endl;
	sum=0;
   }
   //  cout << "efficiency " << sum << endl;
   return sum;  
}

void RooDalitzAmplitude::filldlz(Jpsihh_dlz &dlz, Double_t xmhh, Double_t xcoshh) const
{
   dlz.cospp = xcoshh;
   dlz.mpp = xmhh;
   int nres = _resList->GetSize();

   for(int ir=0; ir<nres; ++ir) {
	for(int ih=0; ih<3; ++ih) {
	   dlz.dre[ir][ih] = 0.0;
	   dlz.dim[ir][ih] = 0.0;
	}
   }
} 

bool RooDalitzAmplitude::checkchange() const
{

   int ir(0);

   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();

	//if (type!=1&&type!=2&&type!=3&&type!=4) continue;
	double m0 = 0;
	double g0 = 0;
	double rg = 0;

	if(type==1) { //breit wigner
	   m0 = ((RooAbsReal&)ires[ires.getSize()-4]).getVal();
	   g0 = ((RooAbsReal&)ires[ires.getSize()-3]).getVal();
	} 
	else if(type==2) { //f0 flatte
	   m0 = ((RooAbsReal&)ires[2]).getVal();
	   g0 = ((RooAbsReal&)ires[3]).getVal();
	   rg = ((RooAbsReal&)ires[4]).getVal();
	} else if(type==10) {
	   for(int it3=0; it3<ires.getSize(); ++it3) {
		if(fabs(_resSpnCache[it3]-((RooAbsReal&)ires[it3]).getVal())>1e-20) {
		   delete coefIter;
		   return true;
		}
	   }
	}
	if( 
		//check if need to update cached amplitude if mass or widht changes
		(fabs(_resParCache[3*ir+0]-m0)>1e-20)
		|| (fabs(_resParCache[3*ir+1]-g0)>1e-20)
		|| (fabs(_resParCache[3*ir+2]-rg)>1e-20) ) {
	   delete coefIter;
	   return true;
	}
	ir++;
   }
   delete coefIter;
   return false;
}

//amplitude for \Cal{H}_Lambda defined in Eq(18) of PLB paper //sqrt(p*q) is taken out to the final calculation.
void RooDalitzAmplitude::amplitude(int Helicity, Jpsihh_dlz &dlz, TComplex &H, TComplex &Hbar) const
{
   H = TComplex(0,0); 
   Hbar = TComplex(0,0);
   if(Helicity!=0&&abs(Helicity)!=1) return;
   double mpp(dlz.mpp);
   //double m2pp = mpp*mpp;
   double costhe = dlz.cospp;

   double re_i, im_i;

   int ir(0);

   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	RooArgList icp = *(RooArgList*)(_cpList->At(ir));
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();

	//if (type!=1&&type!=2&&type!=3&&type!=4) continue;
	double m0 = 0;
	double g0 = 0;
	double rg = 0;


	if(type==1) { //breit wigner
	   m0 = ((RooAbsReal&)ires[ires.getSize()-4]).getVal();
	   g0 = ((RooAbsReal&)ires[ires.getSize()-3]).getVal();
	   //double tap0 = 0;
	   //double tape = 0;
	   //double tapl = 0;
	   //tap0 = ((RooAbsReal&)ires[0]).getVal();
	   //tape = ((RooAbsReal&)ires[2]).getVal();
	   //tapl = ((RooAbsReal&)ires[4]).getVal();
	   //cout<< tap0<<" "<<tape<<" "<<tapl<<endl;
	} 
	else if(type==2) { //f0 flatte
	   m0 = ((RooAbsReal&)ires[2]).getVal();
	   g0 = ((RooAbsReal&)ires[3]).getVal();
	   rg = ((RooAbsReal&)ires[4]).getVal();
	}

	int S = 0; //spin
	if(type==1) {
	   S = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
	}
	//cout << "type spin" << type << " " << S << endl;    
	//spin must >= abs(Helicity)
	if(S<abs(Helicity)) {
	   ir++;
	   continue;
	}

	bool notdefined = (dlz.dre[ir][Helicity+1]==0 && dlz.dim[ir][Helicity+1]==0);
	//    notdefined = 1;
	bool isspline(0);
	if(type==10) {
	   for(int it3=0; it3<ires.getSize(); ++it3) {
		if(fabs(_resSpnCache[it3]-((RooAbsReal&)ires[it3]).getVal())>1e-20) {
		   isspline = 1;
		   break;
		}
	   }
	}

	if( notdefined || isspline
		//check if need to update cached amplitude if mass or widht changes
		|| (fabs(_resParCache[3*ir+0]-m0)>1e-20)
		|| (fabs(_resParCache[3*ir+1]-g0)>1e-20)
		|| (fabs(_resParCache[3*ir+2]-rg)>1e-20) ) {

	   re_i = 0; 
	   im_i = 0;
	   if(type==1) { //breit wigner
		BW_AMP(m0,g0,mpp,costhe,S,Helicity,re_i,im_i);   
	   } else if(type==5&&Helicity==0) {//sigma
		sigmanew_ampl(mpp,re_i,im_i);
	   } else if(type==2&&Helicity==0) { //f0 flatte
		f0_ampl(m0,g0,rg,mpp,re_i,im_i);
	   } else if(type==3&&Helicity==0) { //KM;
		//sigmanew_ampl(mpp,re_i,im_i);
		int ikm = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
		KM_ampl(mpp,re_i,im_i,ikm);
	   } else if(type==4&&Helicity==0) { //noresonace with LB=1
		re_i = 1.0;//getpB(mpp)/m_bs;
		im_i = 0;
	   } else if(type==10&&Helicity==0) {
		spline(mpp, re_i, im_i);
	   }
	   double Bterm;

	   if(type!=10) {Bterm = BTerm(S, mpp, m0);}
	   else { Bterm =1.0;}

	   //cout << "Spin " << S << endl;
	   //cout << "Helicity " << Helicity << endl;
	   //update the cached amplitude 
	   dlz.dre[ir][Helicity+1]=re_i *Bterm;
	   dlz.dim[ir][Helicity+1]=im_i *Bterm;
	   //if(!notdefined)
	   //std::cout << "update " << ir << " Heliticy " << Helicity << " " << dlz.dre[ir][Helicity+1] << std::endl;
	} 
	//std::cout <<"in " << dlz.dre[0][1] << std::endl;
	double factor = 1.0;//sqrt(2.0*S+1.0);
	//double factor = sqrt(2.0*S+1.0);

	H += HHR[ir][Helicity+1]*TComplex(dlz.dre[ir][Helicity+1],dlz.dim[ir][Helicity+1])*factor;
	Hbar += HHRbar[ir][Helicity+1]*TComplex(dlz.dre[ir][Helicity+1],dlz.dim[ir][Helicity+1])*factor;
	ir++;
   }
   delete coefIter; 
} 

//amplitude for \Cal{H}_Lambda defined in Eq(18) of PLB paper //sqrt(p*q) is taken out to the final calculation.
void RooDalitzAmplitude::Amplitude(
	int Helicity, Jpsihh_dlz &dlz, double *A, bool force) const
{

   if(Helicity!=0&&abs(Helicity)!=1) return;
   double mpp(dlz.mpp);
   double costhe = dlz.cospp;
   double re_i, im_i;
   TComplex H(0,0), Hbar(0,0);
   int ir(0);

   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();

	//if (type!=1&&type!=2&&type!=3&&type!=4) continue;
	double m0 = 0;
	double g0 = 0;
	double rg = 0;

	if(type==1) { //breit wigner
	   m0 = ((RooAbsReal&)ires[ires.getSize()-4]).getVal();
	   g0 = ((RooAbsReal&)ires[ires.getSize()-3]).getVal();
	} else if(type==2) { //f0 flatte
	   m0 = ((RooAbsReal&)ires[2]).getVal();
	   g0 = ((RooAbsReal&)ires[3]).getVal();
	   rg = ((RooAbsReal&)ires[4]).getVal();
	}

	int S = 0; //spin
	if(type==1) {
	   S = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
	}
	//cout << "type spin" << type << " " << S << endl;    
	//spin must >= abs(Helicity)
	if(S<abs(Helicity)) {
	   A[ir+1] = 0;
	   ir++;
	   continue;
	}

	bool notdefined = (dlz.dre[ir][Helicity+1]==0 && dlz.dim[ir][Helicity+1]==0);
	//    notdefined = 1;
	bool isspline(0);
	if(type==10) {
	   for(int it3=0; it3<ires.getSize(); ++it3) {
		if(fabs(_resSpnCache[it3]-((RooAbsReal&)ires[it3]).getVal())>1e-20) {
		   isspline = 1;
		   break;
		}
	   }
	}

	if(  force || notdefined || isspline
		//check if need to update cached amplitude if mass or widht changes
		|| (fabs(_resParCache[3*ir+0]-m0)>1e-20)
		|| (fabs(_resParCache[3*ir+1]-g0)>1e-20)
		|| (fabs(_resParCache[3*ir+2]-rg)>1e-20) ) {

	   re_i = 0; 
	   im_i = 0;
	   if(type==1) { //breit wigner
		BW_AMP(m0,g0,mpp, costhe,S,Helicity,re_i,im_i);   
	   }  else if(type==5&&Helicity==0) { //sigma
		sigmanew_ampl(mpp,re_i,im_i);      
	   }  else if(type==2&&Helicity==0) { //f0 flatte
		f0_ampl(m0,g0,rg,mpp,re_i,im_i);
	   } else if(type==3&&Helicity==0) { //sigma
		//        
		int ikm = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
		KM_ampl(mpp,re_i,im_i,ikm);
	   } else if(type==4&&Helicity==0) { //noresonace with LB=1
		re_i = 1.0;// getpB(mpp)/m_bs;
		im_i = 0;
	   } else if(type==10&&Helicity==0) {
		spline(mpp, re_i, im_i);
	   }

	   double Bterm;

	   if(type!=10) {Bterm = BTerm(S, mpp, m0);}
	   else { Bterm =1.0;}

	   //update the cached amplitude 
	   dlz.dre[ir][Helicity+1]=re_i * Bterm;
	   dlz.dim[ir][Helicity+1]=im_i * Bterm;

	} 
	//std::cout <<"in " << dlz.dre[0][1] << std::endl;
	double factor = 1.0;//sqrt(2.0*S+1.0);
	//double factor = sqrt(2.0*S+1.0);
	TComplex hhR     = HelicityCoff(Helicity, ires, S, false);
	TComplex hhRbar  = HelicityCoff(Helicity, ires, S, true);
	TComplex aaR = TransversityCoff(Helicity, ires, S, false);

	H    +=    hhR*TComplex(dlz.dre[ir][Helicity+1],dlz.dim[ir][Helicity+1])*factor;
	Hbar += hhRbar*TComplex(dlz.dre[ir][Helicity+1],dlz.dim[ir][Helicity+1])*factor;
	A[ir+1] = factor*factor*aaR.Rho2()*(pow(dlz.dre[ir][Helicity+1],2)+pow(dlz.dim[ir][Helicity+1],2));
	ir++;
   }
   A[0] = (H.Rho2()+Hbar.Rho2())/2.0;
   delete coefIter; 
} 

//amplitude for \Cal{H}_Lambda defined in Eq(18) of PLB paper //sqrt(p*q) is taken out to the final calculation.
void RooDalitzAmplitude::Interfer(int Helicity, Jpsihh_dlz &dlz, 
	double *A, bool force) const
{

   if(Helicity!=0&&abs(Helicity)!=1) return;
   double mpp(dlz.mpp);
   double costhe = dlz.cospp;
   double re_i, im_i;
   TComplex H(0,0), Hbar(0,0);
   int ir(0);
   TComplex Amp[11];

   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();

	//if (type!=1&&type!=2&&type!=3&&type!=4) continue;
	double m0 = 0;
	double g0 = 0;
	double rg = 0;

	if(type==1) { //breit wigner
	   m0 = ((RooAbsReal&)ires[ires.getSize()-4]).getVal();
	   g0 = ((RooAbsReal&)ires[ires.getSize()-3]).getVal();
	} else if(type==2) { //f0 flatte
	   m0 = ((RooAbsReal&)ires[2]).getVal();
	   g0 = ((RooAbsReal&)ires[3]).getVal();
	   rg = ((RooAbsReal&)ires[4]).getVal();
	}

	int S = 0; //spin
	if(type==1) {
	   S = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
	}
	//    cout << "type spin" << type << " " << S << endl;    
	//spin must >= abs(Helicity)
	if(S<abs(Helicity)) {
	   A[ir+1] = 0;
	   ir++;
	   continue;
	}

	bool notdefined = (dlz.dre[ir][Helicity+1]==0 && dlz.dim[ir][Helicity+1]==0);
	//    notdefined = 1;
	bool isspline(0);
	if(type==10) {
	   for(int it3=0; it3<ires.getSize(); ++it3) {
		if(fabs(_resSpnCache[it3]-((RooAbsReal&)ires[it3]).getVal())>1e-20) {
		   isspline = 1;
		   break;
		}
	   }
	}

	if(  force || notdefined || isspline
		//check if need to update cached amplitude if mass or widht changes
		|| (fabs(_resParCache[3*ir+0]-m0)>1e-20)
		|| (fabs(_resParCache[3*ir+1]-g0)>1e-20)
		|| (fabs(_resParCache[3*ir+2]-rg)>1e-20) ) {

	   re_i = 0; 
	   im_i = 0;
	   if(type==1) { //breit wigner
		BW_AMP(m0,g0,mpp, costhe,S,Helicity,re_i,im_i);   
	   }  else if(type==5) { 
		sigmanew_ampl(mpp,re_i,im_i);
	   }  else if(type==2&&Helicity==0) { //f0 flatte
		f0_ampl(m0,g0,rg,mpp,re_i,im_i);
	   } else if(type==3&&Helicity==0) { //sigma
		int ikm = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
		KM_ampl(mpp,re_i,im_i,ikm);
	   } else if(type==4&&Helicity==0) { //noresonace with LB=1
		re_i = 1.0;// getpB(mpp)/m_bs;
		im_i = 0;
	   } else if(type==10&&Helicity==0) {
		spline(mpp, re_i, im_i);
	   }

	   double Bterm;

	   if(type!=10) {Bterm = BTerm(S, mpp, m0);}
	   else { Bterm =1.0;}

	   //update the cached amplitude 
	   dlz.dre[ir][Helicity+1]=re_i * Bterm;
	   dlz.dim[ir][Helicity+1]=im_i * Bterm;

	} 
	//std::cout <<"in " << dlz.dre[0][1] << std::endl;
	double factor = 1.0;//sqrt(2.0*S+1.0);
	TComplex hhR    = HelicityCoff(Helicity, ires, S, false);
	TComplex hhRbar = HelicityCoff(Helicity, ires, S, true);
	TComplex aaR = TransversityCoff(Helicity, ires, S, false);

	H += hhR*TComplex(dlz.dre[ir][Helicity+1],dlz.dim[ir][Helicity+1])*factor;
	Hbar += hhRbar*TComplex(dlz.dre[ir][Helicity+1],dlz.dim[ir][Helicity+1])*factor;
	Amp[ir] = aaR*TComplex(dlz.dre[ir][Helicity+1],dlz.dim[ir][Helicity+1])*factor;
	ir++;
   }
   A[0] = (H.Rho2()+Hbar.Rho2())/2.0;
   int i_inf = 1;
   int nres= _resList->GetSize();

   for(int i=0; i<nres; ++i) {
	for(int j=i+1; j<nres; ++j) {
	   A[i_inf] =(Amp[i]*Amp[j]).Re();
	   i_inf++;
	}
   }  
   delete coefIter; 
}

Double_t RooDalitzAmplitude::BTerm(Int_t Spin, Double_t mpp, Double_t mr) const
{
   if(_isPHSPGen) { return 1.0;  }
   double c(0);
   int J = Spin;
   int LB = 1;
   //lower value used for 0 and ||
   if(J==1) {
	LB = 0; //changed by LM
   } else if(J==2) {
	LB = 1; //changed by LM
   }

   double pB = getpB(mpp);
   double pB0 = pB;
   if(mr>0.1) pB0 = getpB(mr);
   c = F_BW(_FFB,LB,pB,pB0) * pow(pB/m_bs, LB);
   //LB+1;
   //  c = F_BW(_FFB,LB+1,pB,pB0) * pow(pB/m_bs, LB) *pB/pB0;
   //LB+2;
   //  c = F_BW(_FFB,LB+2,pB,pB0) * pow(pB/m_bs, LB) * pow((pB/pB0),2);  

   return c;
}



//////////////////////////////////////////////////
// Gauss Amplitude for Ks
/////////////////////////////////////////////////
bool RooDalitzAmplitude::GAUSS_AMP(double m_r, double gamma_r, double mpp, double costhe, int J,
	int helz, double &ampl_r, double &ampl_i) const
{
   ampl_r = 0;
   ampl_i = 0;
   double m2pp = mpp*mpp;
   double bw_r(0),bw_i(0);
   gauss_Ks(m_r, gamma_r, m2pp, bw_r, bw_i);
   ampl_r = sqrt(bw_r);
   ampl_i = sqrt(bw_i);
   return true;
}

////////////////////////////////////////////////
//   Gauss function for Ks component
////////////////////////////////////////////////
void RooDalitzAmplitude::gauss_Ks(double m, double gamma, double e2, double &r_ampl, double &i_ampl) const
{
   double de2 = -0.5*pow(((sqrt(e2)-m)/gamma),2);
   double gamma_m = 1/(gamma*sqrt(2*3.14159265358979312));
   double d = gamma_m*exp(de2);
   r_ampl = d;
   i_ampl = 0.0;
}

void RooDalitzAmplitude::CalCoupling() const
{
   int nres = _resList->GetSize();
   for(int i=0; i<nres; ++i) {
	for(int ih=0; ih<3; ++ih) {
	   HHR[i][ih] = TComplex(0.0,0.0);
	   HHRbar[i][ih] = TComplex(0.0,0.0);
	}
   }

   int ir(0);  
   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	RooArgList icp = *(RooArgList*)(_cpList->At(ir));
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();

	int S = 0; //spin
	if(type==1) {
	   S = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
	}
	//    cout << "type spin" << type << " " << S << endl;    
	//spin must >= abs(Helicity)
	//update spline
	if(type==10)    MakeSpline(ires);

	for(int Helicity=-1; Helicity<=1; ++Helicity) {
	   TComplex hhR    = HelicityCoff(Helicity, ires, icp, S);
	   TComplex hhRbar = HelicityCoff(Helicity, ires, icp, S, true);
	   // cout << "hhR " << hhR << endl;
	   //cout << "hhRbar " << hhRbar << endl;
	   HHR[ir][Helicity+1] = hhR;
	   HHRbar[ir][Helicity+1] = hhRbar;
	}

	ir++;
   }
   delete coefIter; 
}

TComplex RooDalitzAmplitude::TransversityCoff(Int_t Helicity, RooArgList ires, Int_t Spin, Bool_t ibar) const
{
   TComplex c(0);
   if(Helicity!=0&&abs(Helicity)!=1) return c;
   if(Spin<abs(Helicity)) return c;
   double pi=TMath::Pi();
   double deg2rad = pi/180.;

   if(Helicity==0) {
	double phi00 = ((RooAbsReal&)ires[1]).getVal()*deg2rad;
	c = TComplex(((RooAbsReal&)ires[0]).getVal(), phi00 , 1);
	//    if(LB>=2) c = c * pow(m_bs/pB0,2);
	if(ibar) {
	   if(Spin==0||Spin==2) c *= -1;  //check for eta_CP
	}
	return c;
   } 
   TComplex ape(0), all(0);

   if(Spin>0) {
	double phipe = ((RooAbsReal&)ires[3]).getVal()*deg2rad;
	double phill = ((RooAbsReal&)ires[5]).getVal()*deg2rad;

	ape = TComplex(((RooAbsReal&)ires[2]).getVal(), phipe , 1)  ;
	all = TComplex(((RooAbsReal&)ires[4]).getVal(), phill , 1) ;
	//  if(LB>=2) all = all * pow(m_bs/pB0,2);
	if(ibar) {
	   if(Spin==1) {
		ape *= -1;
	   } else if(Spin==2) {
		all *= -1;
	   }
	}

	if(Helicity==1) c = all;
	if(Helicity==-1) c = ape;
   }
   return c;
}

TComplex RooDalitzAmplitude::HelicityCoff(Int_t Helicity, RooArgList ires, Int_t Spin, Bool_t ibar) const
{
   TComplex c(0);

   if(Helicity!=0&&abs(Helicity)!=1) return c;
   if(Spin<abs(Helicity)) return c;
   double pi=TMath::Pi();
   double deg2rad = pi/180.;
   int J = Spin;

   if(Helicity==0) {
	double phi00 = ((RooAbsReal&)ires[1]).getVal()*deg2rad;
	c = TComplex(((RooAbsReal&)ires[0]).getVal(), phi00 , 1) ;
	// if(LB>=2) c = c * pow(m_bs/pB0,2);

	if(ibar) {
	   if(Spin==0||Spin==2) c *= -1;  //check for eta_CP
	}
	return c;
   } 
   TComplex ape(0), all(0);

   if(Spin>0) {
	double phipe = ((RooAbsReal&)ires[3]).getVal()*deg2rad;
	double phill = ((RooAbsReal&)ires[5]).getVal()*deg2rad;
	//    int aLB(0);
	ape = TComplex(((RooAbsReal&)ires[2]).getVal(), phipe , 1) ;
	all = TComplex(((RooAbsReal&)ires[4]).getVal(), phill , 1) ;
	//    if(LB>=2) all = all * pow(m_bs/pB0,2); 
	if(ibar) {
	   if(Spin==1) {
		ape *= -1;
	   } else if(Spin==2) {
		all *= -1;
	   }
	}

	if( Helicity==1 ) c = (all + ape)/sqrt(2.0);
	if( Helicity==-1) c = (all - ape)/sqrt(2.0);
   }
   return c;
}

//return for Abar = lambda_CP * A; lambda_CP = |lambda|*exp(-i phi_s);
//phi_s is in rad, phase is in degree
//for B amplitude
TComplex RooDalitzAmplitude::HelicityCoff(Int_t Helicity, RooArgList ires, RooArgList icp, Int_t Spin) const
{
   TComplex c(0);

   if(Helicity!=0&&abs(Helicity)!=1) return c;
   if(Spin<abs(Helicity)) return c;
   double pi=TMath::Pi();
   double deg2rad = pi/180.;
   int J = Spin;

   if(Helicity==0) {
	double phi00 = ((RooAbsReal&)ires[1]).getVal()*deg2rad;
	double phi_s = ((RooAbsReal&)icp[1]).getVal();
	//    cout << "phi_s " << phi_s << endl;
	c = TComplex((1.0+((RooAbsReal&)icp[0]).getVal()), 0.0 , 1) * TComplex(((RooAbsReal&)ires[0]).getVal(), phi00 , 1) ;
	// if(LB>=2) c = c * pow(m_bs/pB0,2);    
	return c;
   } 
   TComplex ape(0), all(0);

   if(Spin>0) {
	double phi_s_pe = ((RooAbsReal&)icp[3]).getVal();
	double phi_s_ll = ((RooAbsReal&)icp[5]).getVal();
	double phipe = ((RooAbsReal&)ires[3]).getVal()*deg2rad;
	double phill = ((RooAbsReal&)ires[5]).getVal()*deg2rad;
	//    int aLB(0);
	ape = TComplex((1.0+((RooAbsReal&)icp[2]).getVal()), 0.0 , 1) * TComplex(((RooAbsReal&)ires[2]).getVal(), phipe , 1);
	all = TComplex((1.0+((RooAbsReal&)icp[4]).getVal()), 0.0 , 1) * TComplex(((RooAbsReal&)ires[4]).getVal(), phill , 1) ;
	//    if(LB>=2) all = all * pow(m_bs/pB0,2); 
	if(Helicity== 1) c = (all + ape)/sqrt(2.0);
	if(Helicity==-1) c = (all - ape)/sqrt(2.0);
   }
   return c;
}


//return for Abar = lambda_CP * A; lambda_CP = |lambda|*exp(-i phi_s);
//phi_s is in rad, phase is in degree
TComplex RooDalitzAmplitude::HelicityCoff(Int_t Helicity, RooArgList ires, RooArgList icp, Int_t Spin, Bool_t ibar) const
{
   TComplex c(0);

   if(Helicity!=0&&abs(Helicity)!=1) return c;
   if(Spin<abs(Helicity)) return c;
   double pi=TMath::Pi();
   double deg2rad = pi/180.;
   int J = Spin;

   if(Helicity==0) {
	double phi00 = ((RooAbsReal&)ires[1]).getVal()*deg2rad;
	double phi_s = ((RooAbsReal&)icp[1]).getVal();
	//    cout << "phi_s " << phi_s << endl;
	c = TComplex((1.0-((RooAbsReal&)icp[0]).getVal()), -phi_s , 1) * TComplex(((RooAbsReal&)ires[0]).getVal(), phi00 , 1) ;
	// if(LB>=2) c = c * pow(m_bs/pB0,2);    
	if(ibar) {
	   if(Spin==0||Spin==2) c *= -1;  //check for eta_CP
	}
	return c;
   } 
   TComplex ape(0), all(0);

   if(Spin>0) {
	double phi_s_pe = ((RooAbsReal&)icp[3]).getVal();
	double phi_s_ll = ((RooAbsReal&)icp[5]).getVal();
	double phipe = ((RooAbsReal&)ires[3]).getVal()*deg2rad;
	double phill = ((RooAbsReal&)ires[5]).getVal()*deg2rad;
	//    int aLB(0);
	//    std::cout << "aLB " << aLB << std::endl;
	ape = TComplex((1.0-((RooAbsReal&)icp[2]).getVal()), -phi_s_pe , 1) * TComplex(((RooAbsReal&)ires[2]).getVal(), phipe , 1) ;
	all = TComplex((1.0-((RooAbsReal&)icp[4]).getVal()), -phi_s_ll , 1) *  TComplex(((RooAbsReal&)ires[4]).getVal(), phill , 1) ;
	//    if(LB>=2) all = all * pow(m_bs/pB0,2); 
	if(ibar) {
	   if(Spin==1) {
		ape *= -1;
	   } else if(Spin==2) {
		all *= -1;
	   }
	}

	if(Helicity==1) c = (all + ape)/sqrt(2.0);
	if(Helicity==-1) c = (all - ape)/sqrt(2.0);
   }
   return c;
}


//Eq(12)&(13)
Double_t RooDalitzAmplitude::Rate(TComplex H0, TComplex Hp, TComplex Hm, Double_t xcosH, Double_t xChi) const
{

   TComplex H0conj = TComplex::Conjugate(H0);
   TComplex Hpconj = TComplex::Conjugate(Hp);
   TComplex Hmconj = TComplex::Conjugate(Hm);
   Double_t cos2 = xcosH*xcosH;
   Double_t sin2 = 1.0-cos2;
   if(_isPHSPGen) return H0.Rho2();
   Double_t term_1 = H0.Rho2()*sin2;
   Double_t term_2 = 0.5*(Hp.Rho2()+Hm.Rho2())*(1.0+cos2);
   TComplex c3 = Hp*Hmconj*TComplex(cos(2.0*xChi),sin(2.0*xChi));
   Double_t term_3 = c3.Re()*sin2;
   TComplex c4 = (H0*Hpconj-H0conj*Hm)*TComplex(cos(-1.0*xChi),sin(-1.0*xChi));
   Double_t term_4 = sqrt(2.0*sin2)*c4.Re()*xcosH;
   return term_1+term_2+term_3+term_4;
}

//Eq(15)
TComplex RooDalitzAmplitude::InterfRate(TComplex H0, TComplex Hp, TComplex Hm, 
	TComplex H0bar, TComplex Hpbar, TComplex Hmbar, 
	Double_t xcosH, Double_t xChi) const
{
   TComplex H0conj = TComplex::Conjugate(H0);
   TComplex Hpconj = TComplex::Conjugate(Hp);
   TComplex Hmconj = TComplex::Conjugate(Hm);
   Double_t cos2 = xcosH*xcosH;
   Double_t sin2 = 1.0-cos2;
   if(_isPHSPGen) return H0bar*H0conj;  
   TComplex term_1 = H0bar*H0conj*sin2;//H0.Rho2()*sin2;
   TComplex term_2 = 0.5*(Hpbar*Hpconj+Hmbar*Hmconj)*(1.0+cos2);
   //  Double_t term_2 = 0.5*(Hp.Rho2()+Hm.Rho2())*(1.0+cos2);
   TComplex term_3 = 0.5*(Hpbar*Hmconj*TComplex(cos(2.0*xChi),sin(2.0*xChi))
	   + Hmbar*Hpconj*TComplex(cos(-2.0*xChi),sin(-2.0*xChi)))*sin2;

   TComplex term_4 = sqrt(0.5*sin2)*((H0bar*Hpconj-Hmbar*H0conj)*TComplex(cos(-1.0*xChi),sin(-1.0*xChi))
	   + (Hpbar*H0conj-H0bar*Hmconj)*TComplex(cos(xChi),sin(xChi)))*xcosH;
   return term_1+term_2+term_3+term_4;
}

//Integration of cosH and chi: |H0|^2*IntcosH(1)+(|H+|^2+|H-|^2)*IntcosH(2)+0.5*Re(H+H-^*)pchi(2)*IntcosH(1)
Double_t RooDalitzAmplitude::RateIntegral(TComplex H0, TComplex Hp, TComplex Hm, Jpsihh_dlz & dlz ) const
{
   //  if(fabs(mpp-0.488984)<0.02) return 0.0;
   TComplex Hmconj = TComplex::Conjugate(Hm);
   double I1, I2, I3;
   if(fabs(dlz.Inte[0])<1.e-10&&fabs(dlz.Inte[1])<1.e-10&&fabs(dlz.Inte[2])<1.e-10) {
	double mpp = dlz.mpp;
	double xcoshh = dlz.cospp;

	I1 = effcosHchiIntegral(1, mpp, xcoshh);
	I2 = effcosHchiIntegral(2, mpp, xcoshh);
	I3 = effcosHchiIntegral(3, mpp, xcoshh);

	dlz.Inte[0]=I1;
	dlz.Inte[1]=I2;
	dlz.Inte[2]=I3;
   } else {

	I1= dlz.Inte[0];
	I2= dlz.Inte[1];
	I3 =dlz.Inte[2];

   }
   Double_t term_1 = H0.Rho2()*I1;
   Double_t term_2 = (Hp.Rho2()+Hm.Rho2())*I2;
   Double_t term_3(0); 
   TComplex c3 = Hp*Hmconj;  
   term_3 = c3.Re()*I3;
   return term_1+term_2+term_3;
}

//Integration of cosH and chi:
TComplex RooDalitzAmplitude::InterfRateIntegral(TComplex H0, TComplex Hp, TComplex Hm, 
	TComplex H0bar, TComplex Hpbar, TComplex Hmbar, 
	Jpsihh_dlz &dlz) const
{
   //  if(fabs(mpp-0.488984)<0.02) return 0.0;
   double I1, I2, I3;
   if(fabs(dlz.Inte[0])<1.e-10&&fabs(dlz.Inte[1])<1.e-10&&fabs(dlz.Inte[2])<1.e-10) {
	double mpp = dlz.mpp;
	double xcoshh = dlz.cospp;

	I1 = effcosHchiIntegral(1, mpp, xcoshh);
	I2 = effcosHchiIntegral(2, mpp, xcoshh);
	I3 = effcosHchiIntegral(3, mpp, xcoshh);

	dlz.Inte[0]=I1;
	dlz.Inte[1]=I2;
	dlz.Inte[2]=I3;
   } else {

	I1= dlz.Inte[0];
	I2= dlz.Inte[1];
	I3 =dlz.Inte[2];

   }
   TComplex H0conj = TComplex::Conjugate(H0);
   TComplex Hpconj = TComplex::Conjugate(Hp);
   TComplex Hmconj = TComplex::Conjugate(Hm);
   TComplex term_1 = H0bar*H0conj*I1;
   TComplex term_2 = (Hpbar*Hpconj+Hmbar*Hmconj)*I2;

   TComplex term_3(0);
   TComplex c3 = 0.5*(Hpbar*Hmconj + Hmbar*Hpconj);
   term_3 = c3*I3;
   return term_1+term_2+term_3;
}

////////////////////////////////////////////////
//   Breit Wigner Resonance
////////////////////////////////////////////////
void RooDalitzAmplitude::breit_wigner(double m, double gamma, double e2, double &r_ampl, double &i_ampl) const
{
   double de2 = m*m-e2; // e2 is m2pp
   double gamma_m = gamma*m;
   double d = (de2*de2+gamma_m*gamma_m);
   r_ampl = de2/d;
   i_ampl = gamma_m/d;
}

/////////////////////////////////////////////
//Blatt-Weisskopf form factors
/////////////////////////////////////////////
Double_t RooDalitzAmplitude::F_BW(double r, int L, double p, double p0) const
{
   double z = pow(r*p,2);
   double z0 = pow(r*p0,2);
   if(L==0) return 1.0;
   if(L==1) return sqrt((1.+z0)/(1.+z));
   if(L==2) return sqrt((z0*z0+3*z0+9.)/(z*z+3*z+9.));
   if(L==3) return sqrt((z0*z0*z0+6*z0*z0+45*z0+225)/(z*z*z+6*z*z+45*z+225));
   return 1.0;
}

///////////////////////////////////////////
//d function d_{i0}^j
////////////////////////////////////////////
Double_t RooDalitzAmplitude::dfun(double c, int i, int j) const
{
   if(j==0) {
	if(i==0) {
	   return 1;
	} else {
	   return 0;
	}
   } else if(j==1) {
	if(i==0) {  //d_00^1
	   return c;
	} else if(i==1) {//d_10^1
	   return -1.0*sqrt(0.5)*sqrt(1.-c*c);
	} else if(i==-1) {
	   return sqrt(0.5)*sqrt(1.-c*c);
	}
   } else if(j==2) {
	if(i==0) {  //d_00^2
	   return 1.5*c*c-0.5;
	} else if(i==1) {//d_10^2
	   return -1.0*sqrt(1.5)*sqrt(1.-c*c)*c;
	} else if(i==-1) {
	   return sqrt(1.5)*sqrt(1.-c*c)*c;
	}
   }
   return 0;
}
Double_t RooDalitzAmplitude::getpB(double mpp) const
{
   return sqrt((m2_bs-(m_jpsi+mpp)*(m_jpsi+mpp))*(m2_bs-(m_jpsi-mpp)*(m_jpsi-mpp)))/2./m_bs;
}
Double_t RooDalitzAmplitude::getpR(double mpp) const
{
   return sqrt(mpp*mpp-4*m2_pi)/2.;
}

//////////////////////////////////////////////////
// Breit Wigner Amplitude
/////////////////////////////////////////////////
bool RooDalitzAmplitude::BW_AMP(double m_r, double gamma_r, double mpp, double costhe, int J,
	int helz, double &ampl_r, double &ampl_i) const
{
   ampl_r = 0;
   ampl_i = 0;
   double m2pp = mpp*mpp;
   if(J>2) return false;
   if(abs(helz)>1) return false;
   if(J==0&&abs(helz)!=0) return true;
   //  int LB = 1;
   int LR = J;
   // if(J==1) {
   //  LB = 0; //changed by LM
   //} else if(J==2) {
   //  LB = 1; //changed by LM
   //}
   //double pB = getpB(mpp);
   double pR = getpR(mpp);
   //double pB0= getpB(m_r);
   //sqrt((m2_bs-(m_jpsi+m_r)*(m_jpsi+m_r))*(m2_bs-(m_jpsi-m_r)*(m_jpsi-m_r)))/2./m_bs;
   double pR0=getpR(m_r);//sqrt(m_r*m_r-4*m2_pi)/2.;

   //double FB = F_BW(_FFB,LB,pB,pB0);
   double FR = F_BW(_FFR,LR,pR,pR0);
   //  std::cout << "_FFR " << _FFR << std::endl;
   //double costhe = (m2p-m2m)*mpp/4./pR/pB/m_bs;
   if(fabs(costhe)>1) std::cout << "costhe is wrong, why?" << std::endl;
   Double_t Tz = 1; 
   if(J>0) {
	Tz = dfun(costhe, -1*helz, J );
   }
   double bw_r(0),bw_i(0);
   double gamma = gamma_r;
   //if(with_dep!=0) gamma = gamma_r*pow((pR/pR0),2*LR+1)*(m_r/mpp)*FR*FR;
   gamma = gamma_r*pow((pR/pR0),2*LR+1)*(m_r/mpp)*FR*FR;
   breit_wigner(m_r, gamma, m2pp, bw_r, bw_i);
   double FFF(1.0);
#ifdef PDG
   FFF = mpp/m_r;
   //std::cout << "FFF" << std::endl;
#endif  

   bw_r *= FR*pow(pR/mpp*FFF,LR);
   bw_i *= FR*pow(pR/mpp*FFF,LR);

   double factor = Tz;
   ampl_r = factor*bw_r;
   ampl_i = factor*bw_i;
   return true;
}

//////////////////////////////////////////////////
// Breit Wigner Amplitude squared
/////////////////////////////////////////////////
double RooDalitzAmplitude::BW2(double m_r, double gamma_r, double mpp, int J, double &ph) const
{
   double m2pp = mpp*mpp;
   if(J>2) return 0.0;
   //  int LB = 1;
   int LR = J;
   double pR = getpR(mpp);
   double pR0= getpR(m_r);//sqrt(m_r*m_r-4*m2_pi)/2.;

   //double FB = F_BW(_FFB,LB,pB,pB0);
   double FR = F_BW(_FFR,LR,pR,pR0);
   double bw_r(0),bw_i(0);
   double gamma = gamma_r;
   //if(with_dep!=0) gamma = gamma_r*pow((pR/pR0),2*LR+1)*(m_r/mpp)*FR*FR;
   gamma = gamma_r*pow((pR/pR0),2*LR+1)*(m_r/mpp)*FR*FR;
   breit_wigner(m_r, gamma, m2pp, bw_r, bw_i);
   double FFF(1.0);
#ifdef PDG
   FFF = mpp/m_r;
   //std::cout << "FFF" << std::endl;
#endif  
   ph = atan2(bw_i, bw_r);
   return pow(FR*pow(pR/mpp*FFF,LR),2)*(bw_r*bw_r+bw_i*bw_i);
}

/*
   double RooDalitzAmplitude::phiSM(double m, double &r_ampl, double &i_ampl) const
   {
   double m2pp = mpp*mpp;
   if(J>2) return 0.0;
//  int LB = 1;
int LR = J;
double pR = getpR(mpp);
double pR0=getpR(m_r);//sqrt(m_r*m_r-4*m2_pi)/2.;

//double FB = F_BW(_FFB,LB,pB,pB0);
double FR = F_BW(_FFR,LR,pR,pR0);
double bw_r(0),bw_i(0);
double gamma = gamma_r;
//if(with_dep!=0) gamma = gamma_r*pow((pR/pR0),2*LR+1)*(m_r/mpp)*FR*FR;
gamma = gamma_r*pow((pR/pR0),2*LR+1)*(m_r/mpp)*FR*FR;
breit_wigner(m_r, gamma, m2pp, bw_r, bw_i);
1./(bw_r*bw_r+bw_i*bw_i);
}
*/

void RooDalitzAmplitude::SMBW2(double m_r, double gamma_r, int J, double mres) const
{
#if 0
   std::cout << "here we are " << std::endl;
   double NN(200000.);
   double aa[200000];
   double ph[200000];
   double min(2.*m_pi), max(m_bs-m_jpsi);
   double mbin = (max-min)/NN;
   double mpp;
   double xph;//phase
   for(int x=0; x<NN; ++x) {
	mpp = min + mbin *((double)x + 0.5);
	aa[x] = BW2(m_r, gamma_r, mpp, J, xph);
	ph[x] = xph;
   }
   double dxmax,smpp,dmpp,w;  
   for(int x=0; x<NN; ++x) {
	mpp = min + mbin *((double)x + 0.5);
	smpp = mres;
	//+/- 5 * resolution region;
	dxmax = (int)(5.*smpp/mbin);
	smpp = smpp*sqrt(2.);
	double sum(0), sumcos(0),sumsin(0);
	for(int dx = -dxmax; dx<= dxmax; ++dx) {
	   if(x+dx>=0&&x+dx<NN) {
		dmpp = mbin*(double)dx;
		dmpp = -pow((dmpp/smpp),2);
		if(dmpp>-9.) {
		   //resolutoin gaus.
		   w = exp(dmpp);
		   sum += w*aa[x+dx];
		   sumsin += w*sqrt(aa[x+dx])*sin(ph[x+dx]);
		   sumcos += w*sqrt(aa[x+dx])*cos(ph[x+dx]);
		}
	   }
	}
	PhiShape[x]=sqrt(sum*(mbin/mres)/sqrt(2.*3.14159265));
	PhiPhase[x] = atan2(sumsin,sumcos);
	//    if(fabs(mpp-0.99)<1e-5||fabs(mpp-1.0)<1e-5||fabs(mpp-1.01)<1e-5||fabs(mpp-1.02)<1e-5||fabs(mpp-1.03)<1e-5||fabs(mpp-1.04)<1e-5||fabs(mpp-1.05)<1e-4) {
	//      std::cout << mpp << " " << aa[x] << " " << pow(PhiShape[x],2) << " " <<  ph[x] << " " << PhiPhase[x]<< std::endl;
	//    }
   }  
#endif
}



//////////////////////////////////////////////////
//        flatte resonance Amplitude
//////////////////////////////////////////////////
void RooDalitzAmplitude::f0_ampl(double m, double gpi, double rgk, double mpp, double &r_ampl, double &i_ampl) const
{
   double mpip = 0.13957061;
   double mpi0 = 0.1349770;
   double mkp = 0.493677;
   double mk0 = 0.497611;

   double mpip2 = mpip*mpip;
   double mpi02 = mpi0*mpi0;
   double mkp2 = mkp*mkp;
   double mk02 = mk0*mk0;
   double mf0 = m;
   double gk = gpi*rgk;

   double mpipi = mpp*mpp;

   //bugg
   double alpha = 2.0;
   double fkk=1.0;
   if(mpipi/4.0>mkp2) {
	double pk2 = fabs(mpipi/4.0-mkp2);
	fkk = exp(-alpha*pk2);
	gk = gk*fkk*fkk;
   }

   r_ampl = 0;
   i_ampl = 0;
   if(1.-4.*mpip2/mpipi<0) return;
   double rhopi = (2.*sqrt(1.-4.*mpip2/mpipi)+sqrt(1.-4.*mpi02/mpipi))/3*mf0*gpi;
   double re=mf0*mf0-mpipi;

   double im = rhopi;

   double rhok;
   //   double factor = sqrt(mpipi/4.-mpip2);
   if(mpipi<4*mkp2) {
	rhok=(sqrt(4.*mkp2/mpipi-1.)+sqrt(4.*mk02/mpipi-1.))/2.*mf0*gk;
	re = re+rhok;
   } else if(mpipi<4*mk02) {
	rhok = sqrt(4.*mk02/mpipi-1)/2.*mf0*gk;
	re = re+rhok;
	im = im+sqrt(1.-4.*mkp2/mpipi)/2.*mf0*gk;
   }  else {
	rhok = (sqrt(1.-4.*mkp2/mpipi)+sqrt(1-4.*mk02/mpipi))/2.*mf0*gk;
	im = im+rhok;
   }

   double d = (re*re+im*im);

   //double pB=getpB(mpp);//sqrt((m2_bs-(m_jpsi+mpp)*(m_jpsi+mpp))*(m2_bs-(m_jpsi-mpp)*(m_jpsi-mpp)))/2./m_bs;
   //double pB0=getpB(m);//sqrt((m2_bs-(m_jpsi+m)*(m_jpsi+m))*(m2_bs-(m_jpsi-m)*(m_jpsi-m)))/2./m_bs;
   //double FB = F_BW(_FFB,1,pB,pB0);
   double factor =1.;// FB*(pB/m_bs);
   r_ampl = factor*(re/d);
   i_ampl = factor*(im/d);
}

//======================
//hep-ph/0608081 for sigma
//=====================
void RooDalitzAmplitude::sigmanew_ampl( double mpp, double &r_ampl, double &i_ampl) const
{
   double mpipi = mpp*mpp;
   double s = mpipi;
   //  double mpp=sqrt(mpipi);

   double mpip = 0.13957061;
   double mpip2 = mpip*mpip;   
   double mKp = 0.493677;
   double mKp2 = mKp*mKp; 
   double mEt = 0.547853;
   double mEt2 = mEt*mEt;

   r_ampl = 0; 
   i_ampl = 0;
   if(1.-4.*mpip2/mpipi<0) return;
   //parameters 
   double b1(1.302), b2(0.340), A(2.426);  
   double alpha(1.3), g4(0.011);
   double sA = 0.41*mpip2;
   double M = 0.953;
   double M2 = M*M;  

   double rhopi = sqrt(1.-4.*mpip2/s);//(2.*sqrt(1.-4.*mpip2/s)
   //+sqrt(1.-4.*mpi02/s))/3.0;
   double rhopi0 = sqrt(1.-4.*mpip2/M2);//(2.*sqrt(1.-4.*mpip2/m2)
   //		   +sqrt(1.-4.*mpi02/m2))/3.0;
   double im(0),re(0);
   double j1 = 2.0+rhopi*log((1-rhopi)/(1+rhopi));
   double j10 = 2.0+rhopi0*log((1-rhopi0)/(1+rhopi0));
   double z = (j1-j10)/TMath::Pi();

   //MGamma_pipi
   double fs = b1+b2*s;
   double g12 = M*fs*exp(-1.0*(s-M2)/A);
   double Albet = g12*(s-sA)/(M2-sA);
   double MG1 = Albet*rhopi;
   im = MG1;
   re = M2-s-Albet*z;

   //MGamma_KK;
   double rhoK = sqrt(fabs(1.-4*mKp2/s));    
   double MG2 = 0.6*g12*(s/M2)*exp(-alpha*fabs(s-4*mKp2))*rhoK;  
   if(1.-4*mKp2/s>0) {
	im += MG2;
   } else {
	re += MG2;
   }
   //MGamma_etaeta
   double rhoE = sqrt(fabs(1.-4*mEt2/s));
   double MG3 = 0.2*g12*(s/M2)*exp(-alpha*fabs(s-4*mEt2))*rhoE;  
   if(1.-4*mEt2/s>0) {
	im += MG3;
   } else {
	re += MG3;
   }
   if(s>16*mpip2) {
	double rho4pi = 1.0/(1+exp(7.082-2.845*s));
	double rho4pi0 = 1.0/(1+exp(7.082-2.845*M2));
	double MG4 = M*g4*rho4pi/rho4pi0;
	im = im+MG4;
   }

   double d = (re*re+im*im);

   //  double pB=getpB(mpp);
   //  double pB0=sqrt((m2_bs-(m_jpsi+m)*(m_jpsi+m))*(m2_bs-(m_jpsi-m)*(m_jpsi-m)))/2./m_bs;
   //  double FB = F_BW(5.0,1,pB,pB0);
   double factor = 1;//(pB/m_bs);
   r_ampl = factor*(re/d);
   i_ampl = factor*(im/d);
} 

void RooDalitzAmplitude::KM_ampl(double mpp, double &r_ampl, double &i_ampl, int ikm) const
{
   double fR[10], fI[10];
   r_ampl = 0;
   i_ampl = 0;
   _myKm.GetValues(mpp,fR,fI);
   if(ikm>=0&&ikm<10) {
	r_ampl = fR[ikm];
	i_ampl = fI[ikm];
   }
   return;
}

void RooDalitzAmplitude::spline(double mpp, double &r_ampl, double &i_ampl) const
{
   r_ampl = 0;
   i_ampl = 0;
   double asp = _sa3.Eval(mpp);
   double psp = _sp3.Eval(mpp);  
   //  std::cout << "Spline called2" << asp << " " << psp  << std::endl;  
   r_ampl = asp;//asp*cos(psp);
   i_ampl = psp;//asp*sin(psp);
   return;
}

void RooDalitzAmplitude::MakeSpline(RooArgList ires) const
{
   double x[NSP], y[NSP], z[NSP];
   double re[NSP], im[NSP];
   double a[NSP], ph[NSP];
   int nsp = ires.getSize()/3-1;
   for(int i=0; i<nsp; ++i) {
	x[i] = ((RooAbsReal&)ires[(i+1)*3+2]).getVal();
	re[i] = ((RooAbsReal&)ires[(i+1)*3]).getVal();  
	im[i] = ((RooAbsReal&)ires[(i+1)*3+1]).getVal();  
   }
   double xmin(2*m_pi), xmax(dlz_hy);
   _sa3 = TSpline3("_sa3",x,re, nsp, "", xmin, xmax);
   _sp3 = TSpline3("_sp3",x,im, nsp, "", xmin, xmax);
   //  std::cout << "Spline " << _sa3.Eval(1.0) << " " << _sp3.Eval(1.0) << std::endl;
   //  std::cout << "Spline maked" << std::endl;
   //std::cout << "Spline called " << sqrt(pow(_sa3.Eval(1.05),1)+pow(_sp3.Eval(1.05),1)) << " " << sqrt(pow(_sa3.Eval(1.045),1)+pow(_sp3.Eval(1.045),1))  << std::endl;
}


//amplitude for \Cal{H}_Lambda defined in Eq(18) of PLB paper //sqrt(p*q) is taken out to the final calculation.
TComplex RooDalitzAmplitude::CalSwave(double mpp) const
{
   double re_i, im_i;
   TComplex H(0,0);
   int ir(0);
   double costhe(0);
   int Helicity(0);
   TIterator* coefIter=_resList->MakeIterator();
   while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
	RooArgList ires = (*Ires);
	int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();

	//if (type!=1&&type!=2&&type!=3&&type!=4) continue;
	double m0 = 0;
	double g0 = 0;
	double rg = 0;

	if(type==1) { //breit wigner
	   m0 = ((RooAbsReal&)ires[ires.getSize()-4]).getVal();
	   g0 = ((RooAbsReal&)ires[ires.getSize()-3]).getVal();
	} else if(type==2) { //f0 flatte
	   m0 = ((RooAbsReal&)ires[2]).getVal();
	   g0 = ((RooAbsReal&)ires[3]).getVal();
	   rg = ((RooAbsReal&)ires[4]).getVal();
	}

	int S = 0; //spin
	if(type==1) {
	   S = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
	}

	//cout << "type spin" << type << " " << S << endl;    
	//spin must >= abs(Helicity)
	if(S!=0) {
	   //      A[ir+1] = 0;
	   ir++;
	   continue;
	}

	re_i = 0; 
	im_i = 0;
	if(type==1) { //breit wigner
	   BW_AMP(m0,g0,mpp, costhe,S,Helicity,re_i,im_i);   
	}  else if(type==2&&Helicity==0) { //f0 flatte
	   f0_ampl(m0,g0,rg,mpp,re_i,im_i);
	} else if(type==5&&Helicity==0) { //sigma
	   sigmanew_ampl(mpp,re_i,im_i);
	} else if(type==4&&Helicity==0) { //noresonace with LB=1
	   re_i = 1.0;// getpB(mpp)/m_bs;
	   im_i = 0;
	}

	//std::cout <<"in " << dlz.dre[0][1] << std::endl;

	TComplex hhR = HelicityCoff(Helicity, ires, S, false);
	double pB = getpB(mpp);
	double pB0 = pB;
	if(m0>0.1) pB0 = getpB(m0);
	double factor = F_BW(_FFB,1,pB,pB0)    ;//sqrt(2.0*S+1.0);    
	H += hhR*TComplex(re_i,im_i)*factor;
	ir++;
   }
   delete coefIter; 
   return H;
} 

void RooDalitzAmplitude::setPHSPGen()
{
   _isPHSPGen = true;
}
