/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODALITZTIMECPCBTAG
#define ROODALITZTIMECPCBTAG

#include "RooAbsAnaConvPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooDalitzAmplitude.h"
#include "RooRealVar.h"
#include "TH2F.h"
//class Jpsihh_dlz;

class RooDalitzTimeCPCBTAG : public RooAbsAnaConvPdf, public RooDalitzAmplitude  {
   public:
	enum DecayType { SingleSided, DoubleSided, Flipped };
	//inline RooDalitzTimeCPCBTAG() {} ; 
	RooDalitzTimeCPCBTAG(const char *name, const char *title,
		RooRealVar& t,
		RooAbsReal& mhh, //m(hh)
		RooAbsReal& coshh, //cos(hh)
		RooAbsReal& cosH, //cos(jpsi)
		RooAbsReal& chi, //chi angle
		TH2F &,
		RooAbsCategory& tag1, RooAbsReal& eta1,
		RooAbsCategory& tag2, RooAbsReal& eta2,		  
		RooArgList efftag,
		RooAbsReal &defftag,		  
		RooArgList Calibtag, RooArgList dCalibtag,
		RooAbsReal& tau, RooAbsReal& dgamma, RooAbsReal& dm, 
		TList *, TList *resList, TList * ,
		double ML, double MR,
		const RooResolutionModel &resModel,
		DecayType dtype=SingleSided,
		double FFR=1.5, double FFB=5.0);
	RooDalitzTimeCPCBTAG(const RooDalitzTimeCPCBTAG& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooDalitzTimeCPCBTAG(*this,newname); }
	virtual ~RooDalitzTimeCPCBTAG() { }

	virtual Double_t coefficient(Int_t basisIndex) const;
	virtual Int_t getCoefAnalyticalIntegral(Int_t coef, RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
	virtual Double_t coefAnalyticalIntegral(Int_t coef, Int_t code, const char* rangeName=0) const ;

	Int_t getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK=kTRUE) const;
	void initGenerator(Int_t code);  
	void generateEvent(Int_t code);

	Double_t sampleEvent();
	//  void setAcccosHFlat();
	void getInt(double *v0int, double *vlint, double* veint, Bool_t force=0, double ylo=0, double yhi=3.0) const;  
	Double_t evaluate(Double_t xt, Double_t xmhh, Double_t xcoshh, 
		Double_t xcosH, Double_t xchi, Int_t xtag);
	Double_t ModT(Double_t xt, Double_t xmhh,
		Double_t xcoshh,
		Double_t xcosH, Double_t xchi);
	Int_t GetTagDec(Int_t tag1, Double_t wtag1,
		Int_t tag2, Double_t wtag2,
		Double_t &wtag);
	void PrintDPInt();                                          
   protected:

	RooRealProxy _t ;
	RooRealProxy _mhh ; 
	RooRealProxy _coshh ;
	RooRealProxy _cosH; //cosTheta_Jpsi
	RooRealProxy _chi; // angle Chi
	TH2F _etapdf;
	RooCategoryProxy _tag1;
	RooRealProxy _eta1;  
	RooCategoryProxy _tag2;
	RooRealProxy _eta2;

	RooListProxy _dCalibtag;  
	RooListProxy _Calibtag;
	RooListProxy _efftag;
	RooRealProxy _RP;
	RooRealProxy _tau ;
	RooRealProxy _dgamma ;
	RooRealProxy _dm ;
	DecayType _dtype;
	RooListProxy _resParams ;
	RooListProxy _cpParams ;


	Int_t _basisCosh;
	Int_t _basisSinh;
	Int_t _basisCos;
	Int_t _basisSin;
	mutable Double_t _Rsum;
	mutable Double_t _Rdif;
	mutable TComplex _RInterf;

	mutable Double_t _RsumInt;
	mutable Double_t _RdifInt;
	mutable TComplex _RInterfInt;
	mutable TComplex HH[4][MYRN][MYRN];
	mutable bool _redoInt;
	//  bool _isPHSPGen;  
	Double_t *_pdfmax;

	mutable Int_t _tag ;  
	mutable Double_t _avgMistag ;
	mutable Double_t _delMistag;    

	Double_t MisTag(int itag) const;
	Double_t delMisTag(int itag) const;
	void CombineTag() const;
	void DPTerms() const;//Double_t &Rsum, Double_t &Rdif, TComplex &RInterf);
	void DPTermsIntegral() const;//Double_t &RsumInt, Double_t & RdifInt, TComplex &RInterfInt) const;
	void DPTermsIntegralMethod1() const;
	double NormalEff();
	Double_t evaluate() const;
	//  void setPHSPGen() const;
   private:
	Double_t tageff() const;
	// ClassDef(RooDalitzTimeCPCBTAG,1) // Your description goes here...
};

#endif
