/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/
#ifndef ROODALITZJPSIHHFF
#define ROODALITZJPSIHHFF

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooArgList.h"
#include "RooAbsCategory.h"
#include "TList.h"
#include "RooListProxy.h"
//#include "RooDalitzJpsihh.h"
//#include <vector>

/*class DMIX_dlz {
public:
  double m2kp;
  double m2pp;
  double dre[25];
  double dim[25];
  DMIX_dlz() {}

private:
  ClassDef(DMIX_dlz, 1);
};
*/
class RooDalitzJpsihhFF : public RooAbsReal {
public:
  RooDalitzJpsihhFF() {} ; 
  RooDalitzJpsihhFF(const char *name, const char *title,
		  TList *_resList
		  );
  RooDalitzJpsihhFF(const RooDalitzJpsihhFF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDalitzJpsihhFF(*this,newname); }
  inline virtual ~RooDalitzJpsihhFF() { }
  /*void breit_wigner(double, double, double, double &,double&) const;
  Double_t F_BW(double, int, double, double) const;
  Double_t dfun(double, int, int) const;
  bool BW_AMP(double, double, double, double, int, int, double &, double &) const;
  void f0_ampl(double, double, double, double, double, double &,double&) const;
  void sigmanew_ampl(double m2p, double m2m, double &re_i, double &im_i) const;
  Bool_t kine_limits(double, double) const;
  Double_t Amplitude(int Helicity, DMIX_dlz&) const;
  void Amplitude(double, double, double *) const;*/
//  double getFF(int IR, double ylo=0, double yhi=5.2) const ;
protected:


  TList *resList;
  RooListProxy resParams ;
  Double_t evaluate() const ;
/*
  Double_t* _resParCache;//       Cache of several resonance parameters.
  int np_dlz;
  double dlz_hx, dlz_lx;
  double dlz_hy, dlz_ly;
  int pdlzl[1001], pdlzr[1001];
  mutable std::vector<DMIX_dlz> pdlz;
  double m_bs;// = 5.3663;
  double m2_bs;// = m_bs*m_bs;
  double m_pi;// = 0.13957018;
  double m2_pi;// = m_pi*m_pi;
  double m_jpsi;// = 3.096916;
  double m2_jpsi;// = m_jpsi*m_jpsi;
  */
private:

//  ClassDef(RooDalitzJpsihhFF,1) // Your description goes here...
};
 

#endif
