/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODALITZFOURV
#define ROODALITZFOURV

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooDalitzAmplitude.h"
#include "RooRealVar.h"
 
//class Jpsihh_dlz;

/* class Jpsihh_dlz { */
/* public: */
/*   double cospp; */
/*   double mpp; */
/*   double dre[10][3]; */
/*   double dim[10][3]; */
/*   Jpsihh_dlz() {} */

/* private: */
/*   ClassDef(Jpsihh_dlz, 1); */
/* }; */

class RooDalitzFourV : public RooAbsPdf, public RooDalitzAmplitude  {
public:
  //inline RooDalitzFourV() {} ; 
  RooDalitzFourV(const char *name, const char *title,
		  RooAbsReal& mhh, //m(hh)
                  RooAbsReal& coshh, //cos(hh)
                  RooAbsReal& cosH, //cos(jpsi)
		  RooAbsReal& chi, //chi angle
		  TList *resList, RooArgList peff, 
		 RooArgList pcosH, RooArgList pchi);
		  
  RooDalitzFourV(const RooDalitzFourV& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDalitzFourV(*this,newname); }
  virtual ~RooDalitzFourV() { }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

  //  Int_t getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK=kTRUE) const;
  //void initGenerator(Int_t code);  
  // void generateEvent(Int_t code);
  // Double_t sampleEvent();
//  void setAcccosHFlat();
  void getInt(double *v0int, double *vlint, double* veint, double ylo=0, double yhi=3.0) const;  
  //Double_t evaluate(Double_t xt, Double_t xmhh, Double_t xcoshh, 
  //		    Double_t xcosH, Double_t xchi, Int_t xtag);
  
protected:

  RooRealProxy _mhh ; 
  RooRealProxy _coshh ;
  RooRealProxy _cosH; //cosTheta_Jpsi
  RooRealProxy _chi; // angle Chi
  RooListProxy _resParams ;
  RooListProxy _peff;
  RooListProxy _pcosH;
  RooListProxy _pchi;
  

  mutable Double_t _Rsum;
  mutable Double_t _RsumInt;

  mutable bool _redoInt;
  Double_t *_pdfmax;

  void DPTerms() const;//Double_t &Rsum, Double_t &Rdif, TComplex &RInterf);
  void DPTermsIntegral() const;//Double_t &RsumInt, Double_t & RdifInt, TComplex &RInterfInt) const;
  Double_t evaluate() const;
private:
  //Double_t tageff() const;
  // ClassDef(RooDalitzFourV,1) // Your description goes here...
};
 
#endif
