 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 
 /*----------------------------Description of the PDf-------------------------
 * This is PDF class for Bs->J/psi Pi Pi Dalitz Plot Fit.
 * It uses 2 invariant masses to describe the amplitude.
 * For signal Amplitude we have used,
 * A(m12,m13) = equation (2) of Physical Review D 78, 072004 (2008)
 * and hence the signal PDF S(m12, m13) = a_i*exp(-i*phi)*A(m12,m13)
 *****************************************************************************/
 
#include "Riostream.h" 

#include "RooDalitzJpsihhFF.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

#include "TIterator.h"

double FFF2;
//ClassImp(RooDalitzJpsihhFF) 
  
RooDalitzJpsihhFF::RooDalitzJpsihhFF(const char *name, const char *title, 
                                 TList *_resList
                                 ) :
  RooAbsReal(name,title), 
  resList(_resList),
  resParams("resParams", "Parameters for resonaces", this)
{ 
  TIterator* coefIter=_resList->MakeIterator();
  while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
    RooArgList ires = (*Ires);
    int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();
    //     std::cout << "type " << type << std::endl;
    //     std::cout  << type << std::endl;
    if (type!=1&&type!=2&&type!=3&&type!=4) continue;
    // double m0 = ((RooAbsReal&)ires[2]).getVal();
    
    if(type==1) { //breit wigner
      resParams.add(ires[0]);
      resParams.add(ires[1]);
      resParams.add(ires[2]);
      resParams.add(ires[3]);
      int Spin = (int)((RooAbsReal&)ires[ires.getSize()-2]).getVal();
      if(Spin>0) {
	resParams.add(ires[4]);
	resParams.add(ires[5]);
	resParams.add(ires[6]);
	resParams.add(ires[7]);
      }
    } else if(type==2) { //f0 flatte
      resParams.add(ires[0]);
      resParams.add(ires[1]);
      resParams.add(ires[2]);
      resParams.add(ires[3]);      
      resParams.add(ires[4]);        
    } else if(type==3||type==4) { //noresonace
      resParams.add(ires[0]);
      resParams.add(ires[1]);
    }
  }
  delete coefIter;

}



RooDalitzJpsihhFF::RooDalitzJpsihhFF(const RooDalitzJpsihhFF& other, const char* name) :  
  RooAbsReal(other,name), 
  resList(other.resList),
  resParams("resParams", this, other.resParams)
{
  
} 

Double_t RooDalitzJpsihhFF::evaluate() const 
{ 
  //f2'(1525) FF lambda=0;
  double cen = 0.460028025;
  double err = 0.104144378;
  double val = FFF2;
  int ir(0);
  double a0(1), al(0), ae(0);
  RooArgList *Ires = (RooArgList*)resList->At( 1 );
//  TIterator* coefIter=resList->MakeIterator();
//  while(RooArgList* Ires = (RooArgList*)coefIter->Next()) {
    RooArgList ires = (*Ires);
    int type = (int)((RooAbsReal&)ires[ires.getSize()-1]).getVal();
  //  if(ir==1) {
       a0 = ((RooAbsReal&)ires[0]).getVal();
       al = ((RooAbsReal&)ires[4]).getVal();
       ae = ((RooAbsReal&)ires[2]).getVal();
    //  break;
//    }
//    ir++;
//  }
//  cout << "FF2 " << val << "a0 a1 " << a0 << " " << a1<< endl;
  //delete coefIter;
  double ratio = ae*ae/(a0*a0+al*al+ae*ae);
  double fe = 0.194;
  double efe = 0.0246;
  return 0.5*(pow((val-cen)/err,2) + pow((ratio-fe)/efe,2));
}


///////////////////////////////////////////////////////////////////////////////


