/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/
#ifndef ROODALITZAMPLITUDE
#define ROODALITZAMPLITUDE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooArgList.h"
#include "RooAbsCategory.h"
#include "TList.h"
#include "RooListProxy.h"
#include "TComplex.h"
#include "RooAbsArg.h"
#include "MyKMatrix.h"
#include "TSpline.h"
#include "TGraph.h"
#include "TPad.h"
#include <memory>
//#include "Jpsihh_dlz.h"

//#include <vector>
#define MYRN 20
#define NSP 100

using namespace std;

class Jpsihh_dlz {
 public:
  double cospp;
  double mpp;
  double dre[MYRN][3];
  double dim[MYRN][3];
  double Inte[3];
  double phsp;
  Jpsihh_dlz() {}
  
 private:
  // ClassDef(Jpsihh_dlz, 1);
};


class RooDalitzAmplitude {
 public:
  RooDalitzAmplitude() {} ; 
  RooDalitzAmplitude(TList *resList,
		     TList *cpList,
		     TList *effList,
		     double ML=0,
		     double MR=3,
		     double FFR=1.5,
		     double FFB=5.0);
  RooDalitzAmplitude(const RooDalitzAmplitude& other) ;
  //virtual TObject* clone(const char* newname) const { return new RooDalitzAmplitude(*this,newname); }
  //virtual ~RooDalitzAmplitude(); 
  virtual ~RooDalitzAmplitude() { 
    std::cout << "begin destruction " <<  std::endl;
    if(pdlz) {
      std::cout << "begin pdlz 1 " << std::endl;
      std::vector<Jpsihh_dlz* >::iterator it;
      for(it = pdlz->begin(); it != pdlz->end(); ++it) {
        delete *it;
        //pdlz->erase(it);        
      } 
      pdlz->clear();
      std::cout << "cleared pdlz " << std::endl;  
   //   delete &pdlz;    
    }
  }

  void breit_wigner(double, double, double, double &,double&) const;
  Double_t F_BW(double, int, double, double) const;
  void gauss_Ks(double, double, double, double &,double&) const;
  bool GAUSS_AMP(double, double, double, double, int, int, double &, double &) const;
  Double_t dfun(double, int, int) const;
  bool BW_AMP(double, double, double, double, int, int, double &, double &) const;
  double BW2(double m_r, double gamma_r, double mpp, int J, double &) const;
  void SMBW2(double m_r, double gamma_r, int J, double mres) const;
  void f0_ampl(double, double, double, double, double &,double&) const;
  void sigmanew_ampl(double, double &,double&) const;  
  Bool_t kine_limits(double, double) const; //for two DP variables
  Bool_t kine_limits(double) const;  //for mhh & coshh, only mhh is needed as input
  void filldlz(Jpsihh_dlz &dlz, Double_t xmhh, Double_t xcoshh) const;
  void amplitude(int Helicity, Jpsihh_dlz &dlz, TComplex &H, TComplex &Hbar) const;
  Double_t Rate(TComplex H0, TComplex Hp, TComplex Hm, Double_t xcosH, Double_t xChi) const;
  Double_t RateIntegral(TComplex H0, TComplex Hp, TComplex Hm, Jpsihh_dlz &) const;
  TComplex InterfRateIntegral(TComplex, TComplex, TComplex, TComplex, TComplex, TComplex, Jpsihh_dlz &) const;
  TComplex InterfRate(TComplex, TComplex, TComplex, TComplex, TComplex, TComplex, Double_t, Double_t) const;
  Double_t getM2Jpsih(double mpp, double cospp) const;
  Double_t ChePol(double, int) const;
  Double_t LegPol(double, int) const;
  Double_t YM(double, double, int, int) const;
  Double_t Seff(double, double ,double, double, int, int, int, int, double) const;
  Double_t efficiency(double mpp, double cospp, double cosh, double xchi, bool def=true) const;
  Double_t YMIntegral(int index, int l, int m) const;
  Double_t effcosHchiIntegral(int index, double xmhh, double xcoshh) const;
  // Double_t getM2Jpsih(double mpp, double cospp) const;
  Double_t getpB(double mpp) const;
  Double_t getpR(double mpp) const;
  Double_t BTerm(Int_t, double, double) const;
  TComplex HelicityCoff(Int_t, RooArgList, Int_t ,Bool_t  ) const;
  TComplex HelicityCoff(Int_t, RooArgList, RooArgList, Int_t ,Bool_t  ) const;  
  TComplex HelicityCoff(Int_t, RooArgList, RooArgList, Int_t   ) const;    
  void Amplitude(int Helicity, Jpsihh_dlz &dlz, double *A, Bool_t force) const;
  void Interfer(int Helicity, Jpsihh_dlz &dlz, double *A, Bool_t force) const;
  TComplex TransversityCoff(Int_t Helicity, RooArgList ires, Int_t Spin,Bool_t ibar) const;
  bool checkchange() const;
  void setACCcosHFlat();
  void CalCoupling() const;
  void setFFR(double a) ;
  void setFFB(double a);
  void KM_ampl(double mpp, double &r_ampl, double &i_ampl, int ikm) const;  
  void spline(double mpp, double &r_ampl, double &i_ampl) const;
  void MakeSpline(RooArgList ires) const;
  TComplex CalSwave(double mpp) const;
  void setPHSPGen();
  void excludeKsRange( int exlKsRange );
  void setKsRange( double mKs_l, double mKs_h );
  
 protected:
  
  TList *_resList;
  TList *_cpList;
  TList *_effList;
  Double_t* _resParCache;//       Cache of several resonance parameters.  
  Double_t* _resSpnCache;
  
  //  Double_t* _resParCachem;//       Cache of several resonance parameters.  
  int np_dlzx,np_dlzy;
  double dlz_hx, dlz_lx; //now it's coshh boundary [-1,1]
  double dlz_hy, dlz_ly; // it's m(hh) fitting region
  double _ML, _MR;
  bool _isPHSPGen;  
  //  mutable std::vector<Jpsihh_dlz> pdlz;
  std::shared_ptr<std::vector<Jpsihh_dlz* > > pdlz;
  mutable TComplex HHR[MYRN][3];
  mutable TComplex HHRbar[MYRN][3];
  double m_bs;   // = 5.3663;
  double m2_bs;  // = m_bs*m_bs;
  double m_pi;   // = 0.13957018;
  double m2_pi;  // = m_pi*m_pi;
  double m_jpsi; // = 3.096916;
  double m2_jpsi;// = m_jpsi*m_jpsi;
  int _iflat; //flag to control acc of cosH;  
  double _FFR, _FFB;

  mutable MyKMatrix _myKm;
  //  mutable TGraph _sa3;
  //  mutable TGraph _sp3;  
  mutable TSpline3 _sa3;
  mutable TSpline3 _sp3;  
 private:
  
  // ClassDef(RooDalitzAmplitude,1) // Your description goes here...
};


#endif
