/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMCCONST
#define ROOMCCONST

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMCConst : public RooAbsReal {
public:
  RooMCConst() {} ; 
  RooMCConst(const char *name, const char *title,
	      RooAbsReal& ,
	      RooAbsReal& ,
	      RooAbsReal &,
	      double *,
	      double *,
	      double *);
  RooMCConst(const RooMCConst& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMCConst(*this,newname); }
  inline virtual ~RooMCConst() { }

protected:

  RooRealProxy aq ;
  RooRealProxy ae ;
  RooRealProxy al ;

  double *aclm;
  double *err;
  double *x0;
  Double_t evaluate() const ;

private:

  //ClassDef(RooMCConst,1) // Your description goes here...
};
 
#endif
