 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 

 #include "RooMCConst.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 #include <math.h> 
 #include "TMath.h" 
 #include "TMatrix.h"
// ClassImp(RooMCConst) 

 RooMCConst::RooMCConst(const char *name, const char *title, 
                        RooAbsReal& _aq,
                        RooAbsReal& _ae,
                        RooAbsReal& _al,
                        double *_aclm,
                        double *_err,
                        double *_x0):
   RooAbsReal(name,title), 
   aq("aq","aq",this,_aq),
   ae("ae","ae",this,_ae),
   al("al","al",this,_al)
 { 
   aclm = new double[9];
   err = new double[9];
   x0 = new double[3];
   for(int i=0;i<9;++i) { aclm[i] = _aclm[i]; err[i] = _err[i];}
   for(int i=0;i<3;++i) { x0[i] = _x0[i];}
 } 


 RooMCConst::RooMCConst(const RooMCConst& other, const char* name) :  
   RooAbsReal(other,name), 
   aq("aq",this,other.aq),
   ae("ae",this,other.ae),   
   al("al",this,other.al)
 { 
   aclm = other.aclm;
   err = other.err;
   x0 = other.x0;
 } 



 Double_t RooMCConst::evaluate() const 
 { 
 /*
   double aclm[9] = {
  1.0, -0.536, -0.642,
  -0.536, 1.0, -0.115,
  -0.642, -0.115, 1.000
};

  double err[9] = {
  1.54429, 0.0,0,
  0.0  , 3.26850e-02, 0,
  0, 0, 3.77161e-03
};*/

   TMatrixD CLM(3,3,aclm), Err(3,3,err);
   TMatrixD EM(3,3);
   EM = Err*CLM*Err;
   //include stat. + sys. errs
   /*
   double cerr[4] = {
      0.0048*0.0048+0.0063*0.0063  ,        0.0048*0.016*(-0.39),
       0.0048*0.016*(-0.39)      ,                0.016*0.016+0.003*0.003
  } ;*/
   TMatrixD EMALL= EM;//(3,3,EM);
   double det2;
   EMALL.Invert(&det2);
   
   double dv[3];
   std::cout << "x0 " << x0[0] << " " << x0[2] << std::endl;
   dv[0] = x0[0] - aq;
   dv[1] = x0[1] - ae;
   dv[2] = x0[2] - al;
   TMatrixD DV(3,1,dv);
   TMatrixD DVT(1,3,dv);
   TMatrixD FErr(1,1);
   FErr = DVT*EMALL*DV;
   return FErr(0,0)/2.;
   
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 1.0 ; 
   
 } 



