 /***************************************************************************** 
  * Project: RooFit                                                           
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 

 #include "RooPhiConstNew.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 #include <math.h> 
 #include "TMath.h" 
 #include "TMatrix.h"
// ClassImp(RooPhiConstNew) 

 RooPhiConstNew::RooPhiConstNew(const char *name, const char *title, 
				  RooAbsReal& _G,
				  RooAbsReal& _dg,
				  RooAbsReal& _phis,
				  RooAbsReal& _lambda,
				  RooAbsReal& _dms,
				  double *_aclm,
				  double *_err,
				  double *_x0):
   RooAbsReal(name,title), 
   G("G","G",this,_G),
   dg("dg","dg",this,_dg),
   phis("phis","phis",this,_phis),
   lambda("lambda","lambda",this,_lambda),
   dms("dms","dms",this,_dms)   
 { 
   aclm = new double[25];
   err = new double[25];
   x0 = new double[5];
   for(int i=0;i<25;++i) { aclm[i] = _aclm[i]; err[i] = _err[i];}
   for(int i=0;i<5;++i) { x0[i] = _x0[i];}
 } 


 RooPhiConstNew::RooPhiConstNew(const RooPhiConstNew& other, const char* name) :  
   RooAbsReal(other,name), 
   G("G",this,other.G),
   dg("dg",this,other.dg),
   phis("phis",this,other.phis),
   lambda("lambda",this,other.lambda),
   dms("dms",this,other.dms)   
 { 
   aclm = other.aclm;
   err = other.err;
   x0 = other.x0;
 } 



 Double_t RooPhiConstNew::evaluate() const 
 { 

   TMatrixD CLM(5,5,aclm), Err(5,5,err);
   TMatrixD EM(5,5);
   EM = Err*CLM*Err;
   //include stat. + sys. errs
   /*
   double cerr[4] = {
      0.0048*0.0048+0.0063*0.0063  ,        0.0048*0.016*(-0.39),
       0.0048*0.016*(-0.39)      ,                0.016*0.016+0.003*0.003
  } ;*/
   TMatrixD EMALL= EM;//(3,3,EM);
   double det2;
   EMALL.Invert(&det2);
   
   double dv[5];
//   std::cout << "x0 " << x0[0] << " " << x0[2] << std::endl;
   dv[0] = x0[0] - G;
   dv[1] = x0[1] - dg;
   dv[2] = x0[2] - phis;
   dv[3] = x0[3] - lambda;
   dv[4] = x0[4] - dms;
   TMatrixD DV(5,1,dv);
   TMatrixD DVT(1,5,dv);
   TMatrixD FErr(1,1);
   FErr = DVT*EMALL*DV;
   return FErr(0,0)/2.;
   
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 1.0 ; 
   
 } 



