/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPHICONST
#define ROOPHICONST

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPhiConst : public RooAbsReal {
public:
  RooPhiConst() {} ; 
  RooPhiConst(const char *name, const char *title,
	      RooAbsReal& _G,
	      RooAbsReal& _dg);
  RooPhiConst(const RooPhiConst& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPhiConst(*this,newname); }
  inline virtual ~RooPhiConst() { }

protected:

  RooRealProxy G ;
  RooRealProxy dg ;
  
  Double_t evaluate() const ;

private:

  //ClassDef(RooPhiConst,1) // Your description goes here...
};
 
#endif
