 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 

 #include "/RooPhiConst.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 #include <math.h> 
 #include "TMath.h" 
 #include "TMatrix.h"
// ClassImp(RooPhiConst) 

 RooPhiConst::RooPhiConst(const char *name, const char *title, 
			  RooAbsReal& _phis,
			  RooAbsReal& _lambda,
			  RooAbsReal& _dms,
			  RooAbsReal& _G,
			  RooAbsReal& _dg):
   RooAbsReal(name,title), 
   phis("phis","phis",this,_phis),
   lambda("lambda","lambda",this,_lambda),
   dms("dms","dms",this,_dms),
   G("G","G",this,_G),
   dg("dg","dg",this,_dg)
 { 
 } 


 RooPhiConst::RooPhiConst(const RooPhiConst& other, const char* name) :  
   RooAbsReal(other,name), 
   phis("phis",this,other.phis),
   lambda("lambda",this,other.lambda),
   dms("dms",this,other.dms),
   G("G",this,other.G),
   dg("dg",this,other.dg)
 { 
 } 


 Double_t RooPhiConst::evaluate() const 
 { 
   //Gs DGs, phis, lambda, dms
   double aclm[25] = {
     1.0, -0.45, +0.01, -0.01, +0.01,
     -0.45, 1.0, -0.08, +0.02, -0.03,
     +0.01, -0.08, 1.0, -0.02, +0.09,
     -0.01, +0.02, -0.02, 1.0, -0.21,
     +0.01, -0.03, +0.09, -0.21, 1.0
   }
  double err[25] = {
    0.0027, 0.0, 0.0, 0.0, 0.0,
    0.0  , 0.0091, 0.0, 0, 0,
    0, 0, 0.049, 0, 0,
    0, 0, 0, 0.019, 0,
    0, 0, 0, 0,  0.056
};
   TMatrixD CLM(5,5,aclm), Err(5,5,err);
   TMatrixD EM(5,5);
   EM = Err*CLM*Err;
   /*
   //include stat. + sys. errs
   double cerr[4] = {
      0.0048*0.0048+0.0063*0.0063  ,        0.0048*0.016*(-0.39),
       0.0048*0.016*(-0.39)      ,                0.016*0.016+0.003*0.003
  } ;
   */
   //   TMatrixD EMALL(2,2,cerr);
   double det2;
   EM.Invert(&det2);
   
   double dv[2];
   dv[0] = 0.6631-G;
   dv[1] = 0.100-dg;
   TMatrixD DV(2,1,dv);
   TMatrixD DVT(1,2,dv);
   TMatrixD FErr(1,1);
   FErr = DVT*EMALL*DV;
   return FErr(0,0)/2.;
   
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 1.0 ; 
   
 } 



