 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 

 #include "RooPhiGDG.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 #include <math.h> 
 #include "TMath.h" 
 #include "TMatrix.h"
// ClassImp(RooPhiGDG) 

 RooPhiGDG::RooPhiGDG(const char *name, const char *title, 
                        RooAbsReal& _G,
                        RooAbsReal& _dg):
   RooAbsReal(name,title), 
   G("G","G",this,_G),
   dg("dg","dg",this,_dg)
 { 
 } 


 RooPhiGDG::RooPhiGDG(const RooPhiGDG& other, const char* name) :  
   RooAbsReal(other,name), 
   G("G",this,other.G),
   dg("dg",this,other.dg)
 { 
 } 



 Double_t RooPhiGDG::evaluate() const 
 { 
   double aclm[4] = {
  1.0, -0.13,
  -0.13, 1.0
};

  double err[4] = {
  sqrt(0.0022*0.0022+0.0015*0.0015), 0.0,
  0.0  , sqrt(0.0073*0.0073+0.0036*0.0036)
};
   TMatrixD CLM(2,2,aclm), Err(2,2,err);
   TMatrixD EMALL(2,2);
   EMALL = Err*CLM*Err;
/*
   //include stat. + sys. errs
   double cerr[4] = {
      0.0048*0.0048+0.0063*0.0063  ,        0.0048*0.016*(-0.39),
       0.0048*0.016*(-0.39)      ,                0.016*0.016+0.003*0.003
  } ;
   TMatrixD EMALL(2,2,cerr);
   */
   
   double det2;
   EMALL.Invert(&det2);
   
   double dv[2];
   dv[0] = 0.6588-G;
   dv[1] = 0.0813-dg;
   TMatrixD DV(2,1,dv);
   TMatrixD DVT(1,2,dv);
   TMatrixD FErr(1,1);
   FErr = DVT*EMALL*DV;
   return FErr(0,0)/2.;
   
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 1.0 ; 
   
 } 



