/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

//#include "Riostream.h" 
#include <iostream> 

#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

Double_t Rhoshape( double m_x )
{ 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

   double m_k = 0.13957061;
   double m_r = 0.77526;
   double wid = 0.14780;
   double m_p = m_k;	

   double m2_r = m_r*m_r;
   double m2_x = m_x*m_x;
   double R  = 3.0;
   double R2 = R*R;
   int Lor = 1;

   //if(m_r<2*m_k||m_x<2*m_k) return 0;
   //double p2_r = m2_r/4.-m2_k;
   //double p2_x = m2_x/4.-m2_k;
   double m2_B = m_B*m_B;
   double p2_r = (m2_r-(m_k+m_p)*(m_k+m_p))*(m2_r-(m_k-m_p)*(m_k-m_p))/(4*m2_r); // MeV^2
   double p2_x = (m2_x-(m_k+m_p)*(m_k+m_p))*(m2_x-(m_k-m_p)*(m_k-m_p))/(4*m2_x);
   double F2_1 = (1.0+R2*p2_r)/(1.0+R2*p2_x);
   double Gamma = wid*pow( sqrt(p2_x/p2_r),2*Lor+1 )*(m_r/m_x)*F2_1;
   
   double pB = sqrt((m2_B-(m_jpsi+m_x)*(m_jpsi+m_x))*(m2_B-(m_jpsi-m_x)*(m_jpsi-m_x)))/2./m_B;;
   double pR = sqrt(p2_x);
   return pB*pR*pow(pR/m_x,2*Lor)*F2_1/(pow((m2_x-m2_r),2)+Gamma*Gamma*m_r*m_r);
   //return pB*pR*pow(pR/m_r,2*Lor)*F2_1/(pow((m2_x-m2_r),2)+Gamma*Gamma*m_r*m_r);
   //return pow(pR,2*Lor+1)*F2_1/(pow((m2_x-m2_r),2)+Gamma*Gamma*m_r*m_r);
 } 

Double_t Phishape( double m_x )
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

   double unit = 1000;
   m_B = 5.27965*unit;
   m_jpsi = 3.096916*unit;
   
   double m_k = 0.493677*unit;
   double m_r = 1019.461;
   double wid = 4.24;
   double m_p = m_k;	

   double m2_r = m_r*m_r;
   double m2_x = m_x*m_x;
   double R  = 1.5*unit;
   double R2 = R*R;
   int Lor = 1;

   double m2_B = m_B*m_B;
   double p2_r = (m2_r-(m_k+m_p)*(m_k+m_p))*(m2_r-(m_k-m_p)*(m_k-m_p))/(4*m2_r); // MeV^2
   double p2_x = (m2_x-(m_k+m_p)*(m_k+m_p))*(m2_x-(m_k-m_p)*(m_k-m_p))/(4*m2_x);
   double F2_1 = (1.0+R2*p2_r)/(1.0+R2*p2_x);
   double Gamma = wid*pow( sqrt(p2_x/p2_r),2*Lor+1 )*(m_r/m_x)*F2_1;
   
   double pB = sqrt((m2_B-(m_jpsi+m_x)*(m_jpsi+m_x))*(m2_B-(m_jpsi-m_x)*(m_jpsi-m_x)))/2./m_B;;
   double pR = sqrt(p2_x);
   return pB*pR*pow(pR/m_x,2*Lor)*F2_1/(pow((m2_x-m2_r),2)+Gamma*Gamma*m_r*m_r);
 } 






