/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooBugg.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TComplex.h"
#include <math.h>
#include "TMath.h"
//#include "GetAmpFactor.C" 

ClassImp(RooBugg);

RooBugg::RooBugg(const char *name, const char *title,
      RooAbsReal& _x,
      RooAbsReal& _RelaAmp,
      RooAbsReal& _RelaPha,
      RooAbsReal& _mMother,
      RooAbsReal& _FBW) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   RelaAmp("RelaAmp","RelaAmp",this,_RelaAmp),
   RelaPha("RelaPha","RelaPha",this,_RelaPha),
   mMother("mMother","mMother",this,_mMother),
   FBW("FBW","FBW",this,_FBW)
{
}


RooBugg::RooBugg(const RooBugg& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   RelaAmp("RelaAmp",this,other.RelaAmp),
   RelaPha("RelaPha",this,other.RelaPha),
   mMother("mMother",this,other.mMother),
   FBW("FBW",this,other.FBW)
{ 
} 

Double_t RooBugg::evaluate() const
{

   double m_B = mMother;
   double m_jpsi = 3.096916;
   double m_pip = 0.13957061;


   //m_bs = 5.2795801;
   //m_jpsi = 3.096900;
   //m2_bs = m_bs*m_bs;

   double mpipi = x*x;
   double s = mpipi;

   double mpip = 0.13957061;
   double mpip2 = mpip*mpip;   
   double mKp = 0.493677;
   double mKp2 = mKp*mKp; 
   double mEt = 0.547853;
   double mEt2 = mEt*mEt;

   double ampl_r = 0; 
   double ampl_i = 0;
   if(1.-4.*mpip2/mpipi<0) return 0;
   //parameters 
   double b1(1.302), b2(0.340), A(2.426);  
   double alpha(1.3), g4(0.011);
   double sA = 0.41*mpip2;
   double M = 0.953;
   double M2 = M*M;  

   double rhopi = sqrt(1.-4.*mpip2/s);//(2.*sqrt(1.-4.*mpip2/s)
   //+sqrt(1.-4.*mpi02/s))/3.0;
   double rhopi0 = sqrt(1.-4.*mpip2/M2);//(2.*sqrt(1.-4.*mpip2/m2)
   //		   +sqrt(1.-4.*mpi02/m2))/3.0;
   double im(0),re(0);
   double j1 = 2.0+rhopi*log((1-rhopi)/(1+rhopi));
   double j10 = 2.0+rhopi0*log((1-rhopi0)/(1+rhopi0));
   double z = (j1-j10)/TMath::Pi();

   //MGamma_pipi
   double fs = b1+b2*s;
   double g12 = M*fs*exp(-1.0*(s-M2)/A);
   double Albet = g12*(s-sA)/(M2-sA);
   double MG1 = Albet*rhopi;
   im = MG1;
   re = M2-s-Albet*z;

   //MGamma_KK;
   double rhoK = sqrt(fabs(1.-4*mKp2/s));    
   double MG2 = 0.6*g12*(s/M2)*exp(-alpha*fabs(s-4*mKp2))*rhoK;  
   if(1.-4*mKp2/s>0) {
      im += MG2;
   } else {
      re += MG2;
   }

   //MGamma_etaeta
   double rhoE = sqrt(fabs(1.-4*mEt2/s));
   double MG3 = 0.2*g12*(s/M2)*exp(-alpha*fabs(s-4*mEt2))*rhoE;  
   if(1.-4*mEt2/s>0) {
      im += MG3;
   } else {
      re += MG3;
   }
   if(s>16*mpip2) {
      double rho4pi = 1.0/(1+exp(7.082-2.845*s));
      double rho4pi0 = 1.0/(1+exp(7.082-2.845*M2));
      double MG4 = M*g4*rho4pi/rho4pi0;
      im = im+MG4;
   }

   double d = (re*re+im*im);

   double pR = getpR( m_pip, x );
   double pB = getpB( m_B, m_jpsi, x );
   //  double pB0=sqrt((m2_bs-(m_jpsi+m)*(m_jpsi+m))*(m2_bs-(m_jpsi-m)*(m_jpsi-m)))/2./m_bs;
   //  double FB = F_BW(5.0,1,pB,pB0);
   double factor = 1;//(pB/m_bs);

   ampl_r = factor*(re/d);
   ampl_i = factor*(im/d);

   TComplex ampl = TComplex(ampl_r,ampl_i);
   TComplex atot = ampl;
   atot = TComplex( RelaAmp, TMath::Pi()/180*RelaPha, 1 )*ampl;
   return atot.Rho2()*pB*pR*factor*factor;

} 

