/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFLATTE
#define ROOFLATTE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooFlatte : public RooAbsPdf {
public:
  RooFlatte() {} ; 
  RooFlatte(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _gpi,
	      RooAbsReal& _rgk,
	      RooAbsReal& _RelaAmp,
	      RooAbsReal& _RelaPha,
	      RooAbsReal& _mMother,
	      RooAbsReal& _FBW,
	      RooAbsReal& _unit);
  RooFlatte(const RooFlatte& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFlatte(*this,newname); }
  inline virtual ~RooFlatte() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy gpi ;
  RooRealProxy rgk ;
  RooRealProxy RelaAmp ;
  RooRealProxy RelaPha ;
  RooRealProxy mMother ;
  RooRealProxy FBW ;
  RooRealProxy unit ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooFlatte,1) // Your description goes here...
};
 
#endif
