/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooFlatte.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "TComplex.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooFlatte); 

 RooFlatte::RooFlatte(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _mean,
                        RooAbsReal& _gpi,
                        RooAbsReal& _rgk,
                        RooAbsReal& _RelaAmp,
                        RooAbsReal& _RelaPha,
                        RooAbsReal& _mMother,
                        RooAbsReal& _FBW,
                        RooAbsReal& _unit) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mean("mean","mean",this,_mean),
   gpi("gpi","gpi",this,_gpi),
   rgk("rgk","rgk",this,_rgk),
   RelaAmp("RelaAmp","RelaAmp",this,_RelaAmp),
   RelaPha("RelaPha","RelaPha",this,_RelaPha),
   mMother("mMother","mMother",this,_mMother),
   FBW("FBW","FBW",this,_FBW),
   unit("unit","unit",this,_unit)
 { 
 } 


 RooFlatte::RooFlatte(const RooFlatte& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mean("mean",this,other.mean),
   gpi("gpi",this,other.gpi),
   rgk("rgk",this,other.rgk),
   RelaAmp("RelaAmp",this,other.RelaAmp),
   RelaPha("RelaPha",this,other.RelaPha),
   mMother("mMother",this,other.mMother),
   FBW("FBW",this,other.FBW),
   unit("unit",this,other.unit)
 { 
 } 

Double_t getpR(double m_k,double m_x)
{
   return sqrt(m_x*m_x-4*m_k*m_k)/2.;
}

Double_t getpB(double m_B,double m_jpsi,double m_x)
{
   double m2_B = m_B*m_B;
   return sqrt((m2_B-(m_jpsi+m_x)*(m_jpsi+m_x))*(m2_B-(m_jpsi-m_x)*(m_jpsi-m_x)))/2./m_B;
}

//Blatt-Weisskopf form factors
Double_t getFBW(double r, int L, double p, double p0) 
{
   double z = pow(r*p,2);
   double z0 = pow(r*p0,2);
   if(L==0) return 1.0;
   if(L==1) return sqrt((1.+z0)/(1.+z));
   if(L==2) return sqrt((z0*z0+3*z0+9.)/(z*z+3*z+9.));
   if(L==3) return sqrt((z0*z0*z0+6*z0*z0+45*z0+225)/(z*z*z+6*z*z+45*z+225));
   return 1.0;
}

Double_t RooFlatte::evaluate() const 
{ 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //--------------------------------------
   // d       MeV^4
   // re      MeV^2
   // gpi     -
   // gk      -
   // factor  MeV^2
   // _FFB    GeV
   //--------------------------------------

   double m_B = mMother;
   double m_jpsi = 3.096916;
   double m_pip = 0.13957061;
   double m_pi0 = 0.1349770;
   double m_kp  = 0.493677;
   double m_k0  = 0.497611;
   double m_eta = 0.547862;

   double m2_pip = m_pip*m_pip;
   double m2_pi0 = m_pi0*m_pi0;
   double m2_kp  = m_kp*m_kp;
   double m2_k0  = m_k0*m_k0;
   double gk  = gpi*rgk;

   double m_r  = mean; // mean value of mass
   double m_x  = x*unit;    // value of mass
   double m2_x = m_x*m_x;

   //bugg
   //double alpha = 2.0; // root-mean-square (rms) size of an emitting source, GeV-2
   //double fkk=1.0;
   //if(m2_x>4*m2_kp) {
   //   double pk2 = fabs(m2_x/4.0-m2_kp);
   //   fkk = exp(-alpha*pk2);
   //   gk = gk*fkk*fkk;
   //}

  
   //if(1.-4*m2_pip/m2_x<0) return 0;
   if( m2_x<4*m2_pip ) return 0;

   double rhopi;
   double m_f;

   // rho_pipi  for f(980) from Bs
   if( m_B > 5.36 ){
	rhopi = (2.*sqrt(1.-4.*m2_pip/m2_x)+sqrt(1.-4.*m2_pi0/m2_x))/3*m_r*gpi; 
	m_f = m_r;
   }
   
   // rho_etapi for a(980) from Bd
   if( m_B < 5.36 ){
	rhopi = sqrt( (1.-pow(m_eta-m_pi0,2)/m2_x)*(1.-pow(m_eta+m_pi0,2)/m2_x) )*gpi;  
	m_f = 1;
   }

   double re = m_r*m_r-m2_x;
   double im = rhopi;
   double rhok;

   // sqrt of a complex number leading to different solutions
   if(m2_x<4*m2_kp) {
	rhok = (sqrt(4.*m2_kp/m2_x-1.)+sqrt(4.*m2_k0/m2_x-1.))/2.*m_f*gk;
	re = re+rhok;
   } else if(m2_x<4*m2_k0) {
	rhok = sqrt(4.*m2_k0/m2_x-1)/2.*m_f*gk;
	re = re+rhok;
	im = im+sqrt(1.-4.*m2_kp/m2_x)/2.*m_f*gk;
   }  else {
	rhok = (sqrt(1.-4.*m2_kp/m2_x)+sqrt(1-4.*m2_k0/m2_x))/2.*m_f*gk;
	im = im+rhok;
   }

   double d  = (re*re+im*im);
   double pR = getpR( m_kp, m_x );
   double pB = getpB( m_B, m_jpsi, m_x );

   //double pB0= getpB( m_B, m_jpsi, m_r );  
   //double _FFB = 5.0;
   //double _FB = getFBW(_FFB,1,pB,pB0);

   double _FB = FBW;
   double factor = _FB*(pB/m_B);

   double ampl_r = re/d;
   double ampl_i = im/d;
  
   //TComplex atot = TComplex( ampl_r, ampl_i ) +TComplex( RelaAmp, -1*TMath::Pi()/180*RelaPha, 1 );
   //TComplex atot = TComplex( ampl_r, ampl_i );
   TComplex atot = TComplex( ampl_r, ampl_i )*TComplex( 1, TMath::Pi()/180*RelaPha, 1 )+TComplex(RelaAmp,0);
   return atot.Rho2()*pB*pR*factor*factor;
}

