/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooRhoGS.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "TComplex.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooRhoGS); 

RooRhoGS::RooRhoGS(const char *name, const char *title, 
      RooAbsReal& _x,
      RooAbsReal& _mean,
      RooAbsReal& _gamma,
      RooAbsReal& _RelaAmp,
      RooAbsReal& _RelaPha,
      RooAbsReal& _mMother,
      double _FFB,
      double _FFR,
      double _LB,
      double _LR) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mean("mean","mean",this,_mean),
   gamma("gamma","gamma",this,_gamma),
   RelaAmp("RelaAmp","RelaAmp",this,_RelaAmp),
   RelaPha("RelaPha","RelaPha",this,_RelaPha),
   mMother("mMother","mMother",this,_mMother),
   FFB(_FFB),FFR(_FFR),LB(_LB),LR(_LR)
{ 
} 


RooRhoGS::RooRhoGS(const RooRhoGS& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mean("mean",this,other.mean),
   gamma("gamma",this,other.gamma),
   RelaAmp("RelaAmp",this,other.RelaAmp),
   RelaPha("RelaPha",this,other.RelaPha),
   mMother("mMother",this,other.mMother),
   FFB(other.FFB), FFR(other.FFR),
   LB(other.LB), LR(other.LR)
{ 
} 

void RooRhoGS::setFFB(double a){
   FFB = a;
}

void RooRhoGS::setFFR(double a){
   FFR = a;
}

Double_t RooRhoGS::evaluate() const 
{ 
   double pi = 3.14159265358979;
   double m_B = mMother;
   double m_jpsi = 3.096916;
   double m_pip = 0.13957061;

   double m_x = x;
   double m_r = mean;

   double m2_r = m_r*m_r;
   double m2_x = m_x*m_x;
   double m2_pip = m_pip*m_pip;

   double p2_x = (m2_x-4.*m2_pip)/4.;
   double p2_r = (m2_r-4.*m2_pip)/4.;
   double p_r = sqrt(p2_r);
   double p_x = sqrt(p2_x);

   double hs = 2./pi*(p_x/m_x)*log((m_x+2.*p_x)/2./m_pip);
   double hm = 2./pi*(p_r/m_r)*log((m_r+2.*p_r)/2./m_pip);

   double dhdq = hm*m2_pip/2/m2_r/p2_r + 1./2./pi/m2_r;
   double f = gamma*m2_r/pow(p_r,3)*( p2_x*(hs-hm) + p2_r*(m2_r-m2_x)*dhdq );

   double gamma_s = gamma*m2_r/m_x*pow(p_x/p_r,3);
   //double F2_1 = (1.0+FFR*FFR*p2_r)/(1.0+FFR*FFR*p2_x);
   //double gamma_s = gamma*m2_r/m_x*pow(p_x/p_r,3)*F2_1;

   double dr = m2_r-m2_x+f;
   double di = gamma_s;

   double ampl_r = dr/(dr*dr+di*di);
   double ampl_i = di/(dr*dr+di*di);

   double pR  = getpR( m_pip, m_x );
   double pR0 = getpR( m_pip, m_r );
   double pB  = getpB( m_B, m_jpsi, m_x );
   double pB0 = getpB( m_B, m_jpsi, m_r );
   double _FB = getFBW( FFB, LB, pB, pB0 );
   double _FR = getFBW( FFR, LR, pR, pR0 );
   double factor = _FB*_FR*pow(pB/m_B,LB)*pow(pR/m_r,LR);

   TComplex ampl = TComplex(ampl_r,ampl_i);
   TComplex atot = TComplex( RelaAmp, TMath::Pi()/180*RelaPha, 1 )*ampl;

   return atot.Rho2()*pB*pR*factor*factor;

}

