/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBUGG
#define ROOBUGG

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBugg : public RooAbsPdf {
public:
  RooBugg() {} ; 
  RooBugg(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _RelaAmp,
	      RooAbsReal& _RelaPha,
	      RooAbsReal& _mMother,
	      RooAbsReal& _FBW);
  RooBugg(const RooBugg& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBugg(*this,newname); }
  inline virtual ~RooBugg() { }

protected:

  RooRealProxy x ;
  RooRealProxy RelaAmp ;
  RooRealProxy RelaPha ;
  RooRealProxy mMother ;
  RooRealProxy FBW ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooBugg,1) // Your description goes here...
};
 
#endif
