/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPHISHAPE
#define ROOPHISHAPE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPhiShape : public RooAbsPdf {
public:
  RooPhiShape() {} ; 
  RooPhiShape(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width,
	      RooAbsReal& _mk,
	      RooAbsReal& _mp,
		RooAbsReal& _mMother,
	      RooAbsReal& _Lor,
	      RooAbsReal& _Radius);
  RooPhiShape(const RooPhiShape& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPhiShape(*this,newname); }
  inline virtual ~RooPhiShape() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  RooRealProxy mk ;
  RooRealProxy mp ;
  RooRealProxy mMother ;
  RooRealProxy Lor ;
  RooRealProxy Radius ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooPhiShape,1) // Your description goes here...
};
 
#endif
