/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

//#include "Riostream.h" 
#include <iostream> 

#include "RooPhiShape.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooPhiShape); 

 RooPhiShape::RooPhiShape(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _mean,
                        RooAbsReal& _width,
                        RooAbsReal& _mk,
                        RooAbsReal& _mp,
                        RooAbsReal& _mMother,
                        RooAbsReal& _Lor,
                        RooAbsReal& _Radius) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mean("mean","mean",this,_mean),
   width("width","width",this,_width),
   mk("mk","mk",this,_mk),
   mp("mp","mp",this,_mp),
   mMother("mMother","mMother",this,_mMother),
   Lor("Lor","Lor",this,_Lor),
   Radius("Radius","Radius",this,_Radius)
 { 
 } 


 RooPhiShape::RooPhiShape(const RooPhiShape& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mean("mean",this,other.mean),
   width("width",this,other.width),
   mk("mk",this,other.mk),
   mp("mp",this,other.mp),
   mMother("mMother",this,other.mMother),
   Lor("Lor",this,other.Lor),
   Radius("Radius",this,other.Radius)
 { 
 } 

 Double_t RooPhiShape::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   double m_B = mMother;
   double m_jpsi = 3.096916;
   double m_k = mk;//0.493677*1000;
   double m_p = mp;	
   double m_r = mean;
   double m_x = x;
   double wid = width;
   double m2_r = m_r*m_r;
   double m2_x = m_x*m_x;
   double R  = Radius;
   double R2 = R*R;

   //if(m_r<2*m_k||m_x<2*m_k) return 0;
   //double p2_r = m2_r/4.-m2_k;
   //double p2_x = m2_x/4.-m2_k;
   double m2_B = m_B*m_B;
   double p2_r = (m2_r-(m_k+m_p)*(m_k+m_p))*(m2_r-(m_k-m_p)*(m_k-m_p))/(4*m2_r); // MeV^2
   double p2_x = (m2_x-(m_k+m_p)*(m_k+m_p))*(m2_x-(m_k-m_p)*(m_k-m_p))/(4*m2_x);
   double F2_1 = (1.0+R2*p2_r)/(1.0+R2*p2_x);
   double Gamma = wid*pow( sqrt(p2_x/p2_r),2*Lor+1 )*(m_r/m_x)*F2_1;
   
   double pB = sqrt((m2_B-(m_jpsi+m_x)*(m_jpsi+m_x))*(m2_B-(m_jpsi-m_x)*(m_jpsi-m_x)))/2./m_B;;
   double pR = sqrt(p2_x);

   //return 1/(pow((m2_x-m2_r),2)+Gamma*Gamma*m_r*m_r);
   return pB*pR*pow(pR/m_r,2*Lor)*F2_1/(pow((m2_x-m2_r),2)+Gamma*Gamma*m_r*m_r);
 } 



