/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROORHOGS
#define ROORHOGS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooRhoGS : public RooAbsPdf {
public:
  RooRhoGS() {} ; 
  RooRhoGS(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _gamma,
	      RooAbsReal& _RelaAmp,
	      RooAbsReal& _RelaPha,
	      RooAbsReal& _mMother,
	      double _FFB,
	      double _FFR,
	      double _LB,
	      double _LR);
  RooRhoGS(const RooRhoGS& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooRhoGS(*this,newname); }
  inline virtual ~RooRhoGS() { }
  
  void setFFR( double a );
  void setFFB( double a );

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy gamma ;
  RooRealProxy RelaAmp ;
  RooRealProxy RelaPha ;
  RooRealProxy mMother ;
  double FFB ;
  double FFR ;
  double LB ;
  double LR ;
 
  Double_t evaluate() const ;

private:

  ClassDef(RooRhoGS,1) // Your description goes here...
};
 
#endif
