/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTMatrix.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "TComplex.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooTMatrix); 

RooTMatrix::RooTMatrix(const char *name, const char *title, 
      RooAbsReal& _x,
      RooAbsReal& _mean,
      RooAbsReal& _gamma,
      RooAbsReal& _RelaAmp,
      RooAbsReal& _RelaPha,
      RooAbsReal& _mMother,
      double _FFB,
      double _FFR,
      double _LB,
      double _LR) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mean("mean","mean",this,_mean),
   gamma("gamma","gamma",this,_gamma),
   RelaAmp("RelaAmp","RelaAmp",this,_RelaAmp),
   RelaPha("RelaPha","RelaPha",this,_RelaPha),
   mMother("mMother","mMother",this,_mMother),
   FFB(_FFB),FFR(_FFR),LB(_LB),LR(_LR)
{ 
} 


RooTMatrix::RooTMatrix(const RooTMatrix& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mean("mean",this,other.mean),
   gamma("gamma",this,other.gamma),
   RelaAmp("RelaAmp",this,other.RelaAmp),
   RelaPha("RelaPha",this,other.RelaPha),
   mMother("mMother",this,other.mMother),
   FFB(other.FFB), FFR(other.FFR),
   LB(other.LB), LR(other.LR)
{ 
} 

void RooTMatrix::setFFB(double a){
   FFB = a;
}

void RooTMatrix::setFFR(double a){
   FFR = a;
}

Double_t RooTMatrix::evaluate() const 
{ 
   double m_B = mMother;
   double m_jpsi = 3.096916;
   double m_pip = 0.13957061;

   double m_r  = mean; // pole mass
   double m_g  = gamma;// width
   double m_x  = x;    // value of mass
   double m2_x = m_x*m_x;

   double pR  = getpR( m_pip, m_x );
   double pR0 = getpR( m_pip, m_r );
   double pB  = getpB( m_B, m_jpsi, m_x );
   double pB0 = getpB( m_B, m_jpsi, m_r );
   double _FB = getFBW( FFB, LB, pB, pB0 );
   double _FR = getFBW( FFR, LR, pR, pR0 );
   double factor = _FB*_FR*pow(pB/m_B,LB)*pow(pR/m_r,LR);

   TComplex ampl = 1./( TComplex(m_r,-1*m_g)*TComplex(m_r,-1*m_g)-TComplex(m_x*m_x,0) );
   TComplex atot = TComplex( RelaAmp, TMath::Pi()/180*RelaPha, 1 )*ampl;
   return atot.Rho2()*pB*pR*factor*factor;
}

