/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTMATRIX
#define ROOTMATRIX

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooTMatrix : public RooAbsPdf {
public:
  RooTMatrix() {} ; 
  RooTMatrix(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _gamma,
	      RooAbsReal& _RelaAmp,
	      RooAbsReal& _RelaPha,
	      RooAbsReal& _mMother,
	      double _FFB,
	      double _FFR,
	      double _LB,
	      double _LR);
  RooTMatrix(const RooTMatrix& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTMatrix(*this,newname); }
  inline virtual ~RooTMatrix() { }
  
  void setFFR( double a );
  void setFFB( double a );

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy gamma ;
  RooRealProxy RelaAmp ;
  RooRealProxy RelaPha ;
  RooRealProxy mMother ;
  double FFB ;
  double FFR ;
  double LB ;
  double LR ;
 
  Double_t evaluate() const ;

private:

  ClassDef(RooTMatrix,1) // Your description goes here...
};
 
#endif
